@extends('layouts.admin')
      @section('title','All Links')
      @section('content')



      <div class="content table-responsive table-full-width">
      <table class="table table-striped">
      <thead>
      <tr>
      <th>Link ID</th>
      <th>Link</th>
      <th>Redirect</th>
      <th>Total Clicks</th>
      <th>Income</th>
      <th><i class="fa fa-pie-chart" aria-hidden="true"></i> </th>
      <th>Created At </th>
      <th>Action </th>
      </tr>
      </thead>

      <tbody>
      @foreach($links as $link)
      <tr>
      <td>{{$link->id}}</td>
            <td>{{url('')}}/{{$link->link}}</td>
                  <td>{{$link->url}} </td>
                        <td>{{            $link->US_visit+
                              $link->CA_visit+
                              $link->GB_visit+
                              $link->AU_visit+
                              $link->DE_visit+
                              $link->NO_visit+
                              $link->AE_visit+
                              $link->SE_visit+
                              $link->ZA_visit+
                              $link->FI_visit+
                              $link->DK_visit+
                              $link->NZ_visit+
                              $link->PL_visit+
                              $link->IE_visit+
                              $link->CH_visit+
                              $link->KW_visit+
                              $link->QA_visit+
                              $link->SA_visit+
                              $link->BE_visit+
                              $link->ES_visit+
                              $link->KR_visit+
                              $link->OM_visit+
                              $link->CY_visit+
                              $link->NL_visit+
                              $link->CZ_visit+
                              $link->IS_visit+
                              $link->LU_visit+
                              $link->GR_visit+
                              $link->FR_visit+
                              $link->SG_visit+
                              $link->IL_visit+
                              $link->JP_visit+
                              $link->MY_visit+
                              $link->NG_visit+
                              $link->PT_visit+
                              $link->IQ_visit+
                              $link->LV_visit+
                              $link->PS_visit+
                              $link->SI_visit+
                              $link->RU_visit+
                              $link->BG_visit+
                              $link->RS_visit+
                              $link->ME_visit+
                              $link->TH_visit+
                              $link->LK_visit+
                              $link->MM_visit+
                              $link->IT_visit+
                              $link->JO_visit+
                              $link->KE_visit+
                              $link->IR_visit+
                              $link->GH_visit+
                              $link->PA_visit+
                              $link->MO_visit+
                              $link->KZ_visit+
                              $link->BD_visit+
                              $link->EE_visit+
                              $link->LT_visit+
                              $link->GE_visit+
                              $link->MX_visit+
                              $link->IO_visit+
                              $link->MD_visit+
                              $link->TZ_visit+
                              $link->INDO_visit+
                              $link->CI_visit+
                              $link->BR_visit+
                              $link->BA_visit+
                              $link->HN_visit+
                              $link->IN_visit+
                              $link->VN_visit+
                              $link->TW_visit+
                              $link->GT_visit+
                              $link->CN_visit+
                              $link->KH_visit+
                              $link->AT_visit+
                              $link->SK_visit+
                              $link->AM_visit+
                              $link->AL_visit+
                              $link->MK_visit+
                              $link->TM_visit+
                              $link->LB_visit+
                              $link->EC_visit+
                              $link->PH_visit+
                              $link->HU_visit+
                              $link->EG_visit+
                              $link->PK_visit+
                              $link->CM_visit+
                              $link->UA_visit+
                              $link->BM_visit+
                              $link->NC_visit+
                              $link->LY_visit+
                              $link->AR_visit+
                              $link->HK_visit+
                              $link->TR_visit+
                              $link->DZ_visit+
                              $link->RO_visit+
                              $link->BS_visit+
                              $link->GL_visit+
                              $link->ZW_visit+
                              $link->LR_visit+
                              $link->MF_visit+
                              $link->BT_visit+
                              $link->GF_visit+
                              $link->NP_visit+
                              $link->AF_visit+
                              $link->CU_visit+
                              $link->SV_visit+
                              $link->SM_visit+
                              $link->others_visit+


                              $link->US_visit_mobile+
                              $link->CA_visit_mobile+
                              $link->GB_visit_mobile+
                              $link->AU_visit_mobile+
                              $link->DE_visit_mobile+
                              $link->NO_visit_mobile+
                              $link->AE_visit_mobile+
                              $link->SE_visit_mobile+
                              $link->ZA_visit_mobile+
                              $link->FI_visit_mobile+
                              $link->DK_visit_mobile+
                              $link->NZ_visit_mobile+
                              $link->PL_visit_mobile+
                              $link->IE_visit_mobile+
                              $link->CH_visit_mobile+
                              $link->KW_visit_mobile+
                              $link->QA_visit_mobile+
                              $link->SA_visit_mobile+
                              $link->BE_visit_mobile+
                              $link->ES_visit_mobile+
                              $link->KR_visit_mobile+
                              $link->OM_visit_mobile+
                              $link->CY_visit_mobile+
                              $link->NL_visit_mobile+
                              $link->CZ_visit_mobile+
                              $link->IS_visit_mobile+
                              $link->LU_visit_mobile+
                              $link->GR_visit_mobile+
                              $link->FR_visit_mobile+
                              $link->SG_visit_mobile+
                              $link->IL_visit_mobile+
                              $link->JP_visit_mobile+
                              $link->MY_visit_mobile+
                              $link->NG_visit_mobile+
                              $link->PT_visit_mobile+
                              $link->IQ_visit_mobile+
                              $link->LV_visit_mobile+
                              $link->PS_visit_mobile+
                              $link->SI_visit_mobile+
                              $link->RU_visit_mobile+
                              $link->BG_visit_mobile+
                              $link->RS_visit_mobile+
                              $link->ME_visit_mobile+
                              $link->TH_visit_mobile+
                              $link->LK_visit_mobile+
                              $link->MM_visit_mobile+
                              $link->IT_visit_mobile+
                              $link->JO_visit_mobile+
                              $link->KE_visit_mobile+
                              $link->IR_visit_mobile+
                              $link->GH_visit_mobile+
                              $link->PA_visit_mobile+
                              $link->MO_visit_mobile+
                              $link->KZ_visit_mobile+
                              $link->BD_visit_mobile+
                              $link->EE_visit_mobile+
                              $link->LT_visit_mobile+
                              $link->GE_visit_mobile+
                              $link->MX_visit_mobile+
                              $link->IO_visit_mobile+
                              $link->MD_visit_mobile+
                              $link->TZ_visit_mobile+
                              $link->INDO_visit_mobile+
                              $link->CI_visit_mobile+
                              $link->BR_visit_mobile+
                              $link->BA_visit_mobile+
                              $link->HN_visit_mobile+
                              $link->IN_visit_mobile+
                              $link->VN_visit_mobile+
                              $link->TW_visit_mobile+
                              $link->GT_visit_mobile+
                              $link->CN_visit_mobile+
                              $link->KH_visit_mobile+
                              $link->AT_visit_mobile+
                              $link->SK_visit_mobile+
                              $link->AM_visit_mobile+
                              $link->AL_visit_mobile+
                              $link->MK_visit_mobile+
                              $link->TM_visit_mobile+
                              $link->LB_visit_mobile+
                              $link->EC_visit_mobile+
                              $link->PH_visit_mobile+
                              $link->HU_visit_mobile+
                              $link->EG_visit_mobile+
                              $link->PK_visit_mobile+
                              $link->CM_visit_mobile+
                              $link->UA_visit_mobile+
                              $link->BM_visit_mobile+
                              $link->NC_visit_mobile+
                              $link->LY_visit_mobile+
                              $link->AR_visit_mobile+
                              $link->HK_visit_mobile+
                              $link->TR_visit_mobile+
                              $link->DZ_visit_mobile+
                              $link->RO_visit_mobile+
                              $link->BS_visit_mobile+
                              $link->GL_visit_mobile+
                              $link->ZW_visit_mobile+
                              $link->LR_visit_mobile+
                              $link->MF_visit_mobile+
                              $link->BT_visit_mobile+
                              $link->GF_visit_mobile+
                              $link->NP_visit_mobile+
                              $link->AF_visit_mobile+
                              $link->CU_visit_mobile+
                              $link->SV_visit_mobile+
                              $link->SM_visit_mobile+
                              $link->others_visit_mobile+

                              $link->US_visit_r+
                              $link->CA_visit_r+
                              $link->GB_visit_r+
                              $link->AU_visit_r+
                              $link->DE_visit_r+
                              $link->NO_visit_r+
                              $link->AE_visit_r+
                              $link->SE_visit_r+
                              $link->ZA_visit_r+
                              $link->FI_visit_r+
                              $link->DK_visit_r+
                              $link->NZ_visit_r+
                              $link->PL_visit_r+
                              $link->IE_visit_r+
                              $link->CH_visit_r+
                              $link->KW_visit_r+
                              $link->QA_visit_r+
                              $link->SA_visit_r+
                              $link->BE_visit_r+
                              $link->ES_visit_r+
                              $link->KR_visit_r+
                              $link->OM_visit_r+
                              $link->CY_visit_r+
                              $link->NL_visit_r+
                              $link->CZ_visit_r+
                              $link->IS_visit_r+
                              $link->LU_visit_r+
                              $link->GR_visit_r+
                              $link->FR_visit_r+
                              $link->SG_visit_r+
                              $link->IL_visit_r+
                              $link->JP_visit_r+
                              $link->MY_visit_r+
                              $link->NG_visit_r+
                              $link->PT_visit_r+
                              $link->IQ_visit_r+
                              $link->LV_visit_r+
                              $link->PS_visit_r+
                              $link->SI_visit_r+
                              $link->RU_visit_r+
                              $link->BG_visit_r+
                              $link->RS_visit_r+
                              $link->ME_visit_r+
                              $link->TH_visit_r+
                              $link->LK_visit_r+
                              $link->MM_visit_r+
                              $link->IT_visit_r+
                              $link->JO_visit_r+
                              $link->KE_visit_r+
                              $link->IR_visit_r+
                              $link->GH_visit_r+
                              $link->PA_visit_r+
                              $link->MO_visit_r+
                              $link->KZ_visit_r+
                              $link->BD_visit_r+
                              $link->EE_visit_r+
                              $link->LT_visit_r+
                              $link->GE_visit_r+
                              $link->MX_visit_r+
                              $link->IO_visit_r+
                              $link->MD_visit_r+
                              $link->TZ_visit_r+
                              $link->INDO_visit_r+
                              $link->CI_visit_r+
                              $link->BR_visit_r+
                              $link->BA_visit_r+
                              $link->HN_visit_r+
                              $link->IN_visit_r+
                              $link->VN_visit_r+
                              $link->TW_visit_r+
                              $link->GT_visit_r+
                              $link->CN_visit_r+
                              $link->KH_visit_r+
                              $link->AT_visit_r+
                              $link->SK_visit_r+
                              $link->AM_visit_r+
                              $link->AL_visit_r+
                              $link->MK_visit_r+
                              $link->TM_visit_r+
                              $link->LB_visit_r+
                              $link->EC_visit_r+
                              $link->PH_visit_r+
                              $link->HU_visit_r+
                              $link->EG_visit_r+
                              $link->PK_visit_r+
                              $link->CM_visit_r+
                              $link->UA_visit_r+
                              $link->BM_visit_r+
                              $link->NC_visit_r+
                              $link->LY_visit_r+
                              $link->AR_visit_r+
                              $link->HK_visit_r+
                              $link->TR_visit_r+
                              $link->DZ_visit_r+
                              $link->RO_visit_r+
                              $link->BS_visit_r+
                              $link->GL_visit_r+
                              $link->ZW_visit_r+
                              $link->LR_visit_r+
                              $link->MF_visit_r+
                              $link->BT_visit_r+
                              $link->GF_visit_r+
                              $link->NP_visit_r+
                              $link->AF_visit_r+
                              $link->CU_visit_r+
                              $link->SV_visit_r+
                              $link->SM_visit_r+
                              $link->others_visit_r+

                              $link->US_visit_mr+
                              $link->CA_visit_mr+
                              $link->GB_visit_mr+
                              $link->AU_visit_mr+
                              $link->DE_visit_mr+
                              $link->NO_visit_mr+
                              $link->AE_visit_mr+
                              $link->SE_visit_mr+
                              $link->ZA_visit_mr+
                              $link->FI_visit_mr+
                              $link->DK_visit_mr+
                              $link->NZ_visit_mr+
                              $link->PL_visit_mr+
                              $link->IE_visit_mr+
                              $link->CH_visit_mr+
                              $link->KW_visit_mr+
                              $link->QA_visit_mr+
                              $link->SA_visit_mr+
                              $link->BE_visit_mr+
                              $link->ES_visit_mr+
                              $link->KR_visit_mr+
                              $link->OM_visit_mr+
                              $link->CY_visit_mr+
                              $link->NL_visit_mr+
                              $link->CZ_visit_mr+
                              $link->IS_visit_mr+
                              $link->LU_visit_mr+
                              $link->GR_visit_mr+
                              $link->FR_visit_mr+
                              $link->SG_visit_mr+
                              $link->IL_visit_mr+
                              $link->JP_visit_mr+
                              $link->MY_visit_mr+
                              $link->NG_visit_mr+
                              $link->PT_visit_mr+
                              $link->IQ_visit_mr+
                              $link->LV_visit_mr+
                              $link->PS_visit_mr+
                              $link->SI_visit_mr+
                              $link->RU_visit_mr+
                              $link->BG_visit_mr+
                              $link->RS_visit_mr+
                              $link->ME_visit_mr+
                              $link->TH_visit_mr+
                              $link->LK_visit_mr+
                              $link->MM_visit_mr+
                              $link->IT_visit_mr+
                              $link->JO_visit_mr+
                              $link->KE_visit_mr+
                              $link->IR_visit_mr+
                              $link->GH_visit_mr+
                              $link->PA_visit_mr+
                              $link->MO_visit_mr+
                              $link->KZ_visit_mr+
                              $link->BD_visit_mr+
                              $link->EE_visit_mr+
                              $link->LT_visit_mr+
                              $link->GE_visit_mr+
                              $link->MX_visit_mr+
                              $link->IO_visit_mr+
                              $link->MD_visit_mr+
                              $link->TZ_visit_mr+
                              $link->INDO_visit_mr+
                              $link->CI_visit_mr+
                              $link->BR_visit_mr+
                              $link->BA_visit_mr+
                              $link->HN_visit_mr+
                              $link->IN_visit_mr+
                              $link->VN_visit_mr+
                              $link->TW_visit_mr+
                              $link->GT_visit_mr+
                              $link->CN_visit_mr+
                              $link->KH_visit_mr+
                              $link->AT_visit_mr+
                              $link->SK_visit_mr+
                              $link->AM_visit_mr+
                              $link->AL_visit_mr+
                              $link->MK_visit_mr+
                              $link->TM_visit_mr+
                              $link->LB_visit_mr+
                              $link->EC_visit_mr+
                              $link->PH_visit_mr+
                              $link->HU_visit_mr+
                              $link->EG_visit_mr+
                              $link->PK_visit_mr+
                              $link->CM_visit_mr+
                              $link->UA_visit_mr+
                              $link->BM_visit_mr+
                              $link->NC_visit_mr+
                              $link->LY_visit_mr+
                              $link->AR_visit_mr+
                              $link->HK_visit_mr+
                              $link->TR_visit_mr+
                              $link->DZ_visit_mr+
                              $link->RO_visit_mr+
                              $link->BS_visit_mr+
                              $link->GL_visit_mr+
                              $link->ZW_visit_mr+
                              $link->LR_visit_mr+
                              $link->MF_visit_mr+
                              $link->BT_visit_mr+
                              $link->GF_visit_mr+
                              $link->NP_visit_mr+
                              $link->AF_visit_mr+
                              $link->CU_visit_mr+
                              $link->SV_visit_mr+
                              $link->SM_visit_mr+
                              $link->others_visit_mr}}</td>
                              <td>{{$link->US_visit*$countries->US/1000+         
                                    $link->CA_visit*$countries->CA/1000+
                                    $link->GB_visit*$countries->GB/1000+
                                    $link->AU_visit*$countries->AU/1000+
                                    $link->DE_visit*$countries->DE/1000+
                                    $link->NO_visit*$countries->NO/1000+
                                    $link->AE_visit*$countries->AE/1000+
                                    $link->SE_visit*$countries->SE/1000+
                                    $link->ZA_visit*$countries->ZA/1000+
                                    $link->FI_visit*$countries->FI/1000+
                                    $link->DK_visit*$countries->DK/1000+
                                    $link->NZ_visit*$countries->NZ/1000+
                                    $link->PL_visit*$countries->PL/1000+
                                    $link->IE_visit*$countries->IE/1000+
                                    $link->CH_visit*$countries->CH/1000+
                                    $link->KW_visit*$countries->KW/1000+
                                    $link->QA_visit*$countries->QA/1000+
                                    $link->SA_visit*$countries->SA/1000+
                                    $link->BE_visit*$countries->BE/1000+
                                    $link->ES_visit*$countries->ES/1000+
                                    $link->KR_visit*$countries->KR/1000+
                                    $link->OM_visit*$countries->OM/1000+
                                    $link->CY_visit*$countries->CY/1000+
                                    $link->NL_visit*$countries->NL/1000+
                                    $link->CZ_visit*$countries->CZ/1000+
                                    $link->IS_visit*$countries->IS/1000+
                                    $link->LU_visit*$countries->LU/1000+
                                    $link->GR_visit*$countries->GR/1000+
                                    $link->FR_visit*$countries->FR/1000+
                                    $link->SG_visit*$countries->SG/1000+
                                    $link->IL_visit*$countries->IL/1000+
                                    $link->JP_visit*$countries->JP/1000+
                                    $link->MY_visit*$countries->MY/1000+
                                    $link->NG_visit*$countries->NG/1000+
                                    $link->PT_visit*$countries->PT/1000+
                                    $link->IQ_visit*$countries->IQ/1000+
                                    $link->LV_visit*$countries->LV/1000+
                                    $link->PS_visit*$countries->PS/1000+
                                    $link->SI_visit*$countries->SI/1000+
                                    $link->RU_visit*$countries->RU/1000+
                                    $link->BG_visit*$countries->BG/1000+
                                    $link->RS_visit*$countries->RS/1000+
                                    $link->ME_visit*$countries->ME/1000+
                                    $link->TH_visit*$countries->TH/1000+
                                    $link->LK_visit*$countries->LK/1000+
                                    $link->MM_visit*$countries->MM/1000+
                                    $link->IT_visit*$countries->IT/1000+
                                    $link->JO_visit*$countries->JO/1000+
                                    $link->KE_visit*$countries->KE/1000+
                                    $link->IR_visit*$countries->IR/1000+
                                    $link->GH_visit*$countries->GH/1000+
                                    $link->PA_visit*$countries->PA/1000+
                                    $link->MO_visit*$countries->MO/1000+
                                    $link->KZ_visit*$countries->KZ/1000+
                                    $link->BD_visit*$countries->BD/1000+
                                    $link->EE_visit*$countries->EE/1000+
                                    $link->LT_visit*$countries->LT/1000+
                                    $link->GE_visit*$countries->GE/1000+
                                    $link->MX_visit*$countries->MX/1000+
                                    $link->IO_visit*$countries->IO/1000+
                                    $link->MD_visit*$countries->MD/1000+
                                    $link->TZ_visit*$countries->TZ/1000+
                                    $link->INDO_visit*$countries->INDO/1000+
                                    $link->CI_visit*$countries->CI/1000+
                                    $link->BR_visit*$countries->BR/1000+
                                    $link->BA_visit*$countries->BA/1000+
                                    $link->HN_visit*$countries->HN/1000+
                                    $link->IN_visit*$countries->IN/1000+
                                    $link->VN_visit*$countries->VN/1000+
                                    $link->TW_visit*$countries->TW/1000+
                                    $link->GT_visit*$countries->GT/1000+
                                    $link->CN_visit*$countries->CN/1000+
                                    $link->KH_visit*$countries->KH/1000+
                                    $link->AT_visit*$countries->AT/1000+
                                    $link->SK_visit*$countries->SK/1000+
                                    $link->AM_visit*$countries->AM/1000+
                                    $link->AL_visit*$countries->AL/1000+
                                    $link->MK_visit*$countries->MK/1000+
                                    $link->TM_visit*$countries->TM/1000+
                                    $link->LB_visit*$countries->LB/1000+
                                    $link->EC_visit*$countries->EC/1000+
                                    $link->PH_visit*$countries->PH/1000+
                                    $link->HU_visit*$countries->HU/1000+
                                    $link->EG_visit*$countries->EG/1000+
                                    $link->PK_visit*$countries->PK/1000+
                                    $link->CM_visit*$countries->CM/1000+
                                    $link->UA_visit*$countries->UA/1000+
                                    $link->BM_visit*$countries->BM/1000+
                                    $link->NC_visit*$countries->NC/1000+
                                    $link->LY_visit*$countries->LY/1000+
                                    $link->AR_visit*$countries->AR/1000+
                                    $link->HK_visit*$countries->HK/1000+
                                    $link->TR_visit*$countries->TR/1000+
                                    $link->DZ_visit*$countries->DZ/1000+
                                    $link->RO_visit*$countries->RO/1000+
                                    $link->BS_visit*$countries->BS/1000+
                                    $link->GL_visit*$countries->GL/1000+
                                    $link->ZW_visit*$countries->ZW/1000+
                                    $link->LR_visit*$countries->LR/1000+
                                    $link->MF_visit*$countries->MF/1000+
                                    $link->BT_visit*$countries->BT/1000+
                                    $link->GF_visit*$countries->GF/1000+
                                    $link->NP_visit*$countries->NP/1000+
                                    $link->AF_visit*$countries->AF/1000+
                                    $link->CU_visit*$countries->CU/1000+
                                    $link->SV_visit*$countries->SV/1000+
                                    $link->SM_visit*$countries->SM/1000+
                                    $link->others_visit*$countries->others/1000+
                                    $link->US_visit_mobile*$countries->US_m/1000+
                                    $link->CA_visit_mobile*$countries->CA_m/1000+
                                    $link->GB_visit_mobile*$countries->GB_m/1000+
                                    $link->AU_visit_mobile*$countries->AU_m/1000+
                                    $link->DE_visit_mobile*$countries->DE_m/1000+
                                    $link->NO_visit_mobile*$countries->NO_m/1000+
                                    $link->AE_visit_mobile*$countries->AE_m/1000+
                                    $link->SE_visit_mobile*$countries->SE_m/1000+
                                    $link->ZA_visit_mobile*$countries->ZA_m/1000+
                                    $link->FI_visit_mobile*$countries->FI_m/1000+
                                    $link->DK_visit_mobile*$countries->DK_m/1000+
                                    $link->NZ_visit_mobile*$countries->NZ_m/1000+
                                    $link->PL_visit_mobile*$countries->PL_m/1000+
                                    $link->IE_visit_mobile*$countries->IE_m/1000+
                                    $link->CH_visit_mobile*$countries->CH_m/1000+
                                    $link->KW_visit_mobile*$countries->KW_m/1000+
                                    $link->QA_visit_mobile*$countries->QA_m/1000+
                                    $link->SA_visit_mobile*$countries->SA_m/1000+
                                    $link->BE_visit_mobile*$countries->BE_m/1000+
                                    $link->ES_visit_mobile*$countries->ES_m/1000+
                                    $link->KR_visit_mobile*$countries->KR_m/1000+
                                    $link->OM_visit_mobile*$countries->OM_m/1000+
                                    $link->CY_visit_mobile*$countries->CY_m/1000+
                                    $link->NL_visit_mobile*$countries->NL_m/1000+
                                    $link->CZ_visit_mobile*$countries->CZ_m/1000+
                                    $link->IS_visit_mobile*$countries->IS_m/1000+
                                    $link->LU_visit_mobile*$countries->LU_m/1000+
                                    $link->GR_visit_mobile*$countries->GR_m/1000+
                                    $link->FR_visit_mobile*$countries->FR_m/1000+
                                    $link->SG_visit_mobile*$countries->SG_m/1000+
                                    $link->IL_visit_mobile*$countries->IL_m/1000+
                                    $link->JP_visit_mobile*$countries->JP_m/1000+
                                    $link->MY_visit_mobile*$countries->MY_m/1000+
                                    $link->NG_visit_mobile*$countries->NG_m/1000+
                                    $link->PT_visit_mobile*$countries->PT_m/1000+
                                    $link->IQ_visit_mobile*$countries->IQ_m/1000+
                                    $link->LV_visit_mobile*$countries->LV_m/1000+
                                    $link->PS_visit_mobile*$countries->PS_m/1000+
                                    $link->SI_visit_mobile*$countries->SI_m/1000+
                                    $link->RU_visit_mobile*$countries->RU_m/1000+
                                    $link->BG_visit_mobile*$countries->BG_m/1000+
                                    $link->RS_visit_mobile*$countries->RS_m/1000+
                                    $link->ME_visit_mobile*$countries->ME_m/1000+
                                    $link->TH_visit_mobile*$countries->TH_m/1000+
                                    $link->LK_visit_mobile*$countries->LK_m/1000+
                                    $link->MM_visit_mobile*$countries->MM_m/1000+
                                    $link->IT_visit_mobile*$countries->IT_m/1000+
                                    $link->JO_visit_mobile*$countries->JO_m/1000+
                                    $link->KE_visit_mobile*$countries->KE_m/1000+
                                    $link->IR_visit_mobile*$countries->IR_m/1000+
                                    $link->GH_visit_mobile*$countries->GH_m/1000+
                                    $link->PA_visit_mobile*$countries->PA_m/1000+
                                    $link->MO_visit_mobile*$countries->MO_m/1000+
                                    $link->KZ_visit_mobile*$countries->KZ_m/1000+
                                    $link->BD_visit_mobile*$countries->BD_m/1000+
                                    $link->EE_visit_mobile*$countries->EE_m/1000+
                                    $link->LT_visit_mobile*$countries->LT_m/1000+
                                    $link->GE_visit_mobile*$countries->GE_m/1000+
                                    $link->MX_visit_mobile*$countries->MX_m/1000+
                                    $link->IO_visit_mobile*$countries->IO_m/1000+
                                    $link->MD_visit_mobile*$countries->MD_m/1000+
                                    $link->TZ_visit_mobile*$countries->TZ_m/1000+
                                    $link->INDO_visit_mobile*$countries->INDO_m/1000+
                                    $link->CI_visit_mobile*$countries->CI_m/1000+
                                    $link->BR_visit_mobile*$countries->BR_m/1000+
                                    $link->BA_visit_mobile*$countries->BA_m/1000+
                                    $link->HN_visit_mobile*$countries->HN_m/1000+
                                    $link->IN_visit_mobile*$countries->IN_m/1000+
                                    $link->VN_visit_mobile*$countries->VN_m/1000+
                                    $link->TW_visit_mobile*$countries->TW_m/1000+
                                    $link->GT_visit_mobile*$countries->GT_m/1000+
                                    $link->CN_visit_mobile*$countries->CN_m/1000+
                                    $link->KH_visit_mobile*$countries->KH_m/1000+
                                    $link->AT_visit_mobile*$countries->AT_m/1000+
                                    $link->SK_visit_mobile*$countries->SK_m/1000+
                                    $link->AM_visit_mobile*$countries->AM_m/1000+
                                    $link->AL_visit_mobile*$countries->AL_m/1000+
                                    $link->MK_visit_mobile*$countries->MK_m/1000+
                                    $link->TM_visit_mobile*$countries->TM_m/1000+
                                    $link->LB_visit_mobile*$countries->LB_m/1000+
                                    $link->EC_visit_mobile*$countries->EC_m/1000+
                                    $link->PH_visit_mobile*$countries->PH_m/1000+
                                    $link->HU_visit_mobile*$countries->HU_m/1000+
                                    $link->EG_visit_mobile*$countries->EG_m/1000+
                                    $link->PK_visit_mobile*$countries->PK_m/1000+
                                    $link->CM_visit_mobile*$countries->CM_m/1000+
                                    $link->UA_visit_mobile*$countries->UA_m/1000+
                                    $link->BM_visit_mobile*$countries->BM_m/1000+
                                    $link->NC_visit_mobile*$countries->NC_m/1000+
                                    $link->LY_visit_mobile*$countries->LY_m/1000+
                                    $link->AR_visit_mobile*$countries->AR_m/1000+
                                    $link->HK_visit_mobile*$countries->HK_m/1000+
                                    $link->TR_visit_mobile*$countries->TR_m/1000+
                                    $link->DZ_visit_mobile*$countries->DZ_m/1000+
                                    $link->RO_visit_mobile*$countries->RO_m/1000+
                                    $link->BS_visit_mobile*$countries->BS_m/1000+
                                    $link->GL_visit_mobile*$countries->GL_m/1000+
                                    $link->ZW_visit_mobile*$countries->ZW_m/1000+
                                    $link->LR_visit_mobile*$countries->LR_m/1000+
                                    $link->MF_visit_mobile*$countries->MF_m/1000+
                                    $link->BT_visit_mobile*$countries->BT_m/1000+
                                    $link->GF_visit_mobile*$countries->GF_m/1000+
                                    $link->NP_visit_mobile*$countries->NP_m/1000+
                                    $link->AF_visit_mobile*$countries->AF_m/1000+
                                    $link->CU_visit_mobile*$countries->CU_m/1000+
                                    $link->SV_visit_mobile*$countries->SV_m/1000+
                                    $link->SM_visit_mobile*$countries->SM_m/1000+
                                    $link->others_visit_mobile*$countries->others_m/1000+
                                    $link->US_visit_r*$countries->US_r/1000+
                                    $link->CA_visit_r*$countries->CA_r/1000+
                                    $link->GB_visit_r*$countries->GB_r/1000+
                                    $link->AU_visit_r*$countries->AU_r/1000+
                                    $link->DE_visit_r*$countries->DE_r/1000+
                                    $link->NO_visit_r*$countries->NO_r/1000+
                                    $link->AE_visit_r*$countries->AE_r/1000+
                                    $link->SE_visit_r*$countries->SE_r/1000+
                                    $link->ZA_visit_r*$countries->ZA_r/1000+
                                    $link->FI_visit_r*$countries->FI_r/1000+
                                    $link->DK_visit_r*$countries->DK_r/1000+
                                    $link->NZ_visit_r*$countries->NZ_r/1000+
                                    $link->PL_visit_r*$countries->PL_r/1000+
                                    $link->IE_visit_r*$countries->IE_r/1000+
                                    $link->CH_visit_r*$countries->CH_r/1000+
                                    $link->KW_visit_r*$countries->KW_r/1000+
                                    $link->QA_visit_r*$countries->QA_r/1000+
                                    $link->SA_visit_r*$countries->SA_r/1000+
                                    $link->BE_visit_r*$countries->BE_r/1000+
                                    $link->ES_visit_r*$countries->ES_r/1000+
                                    $link->KR_visit_r*$countries->KR_r/1000+
                                    $link->OM_visit_r*$countries->OM_r/1000+
                                    $link->CY_visit_r*$countries->CY_r/1000+
                                    $link->NL_visit_r*$countries->NL_r/1000+
                                    $link->CZ_visit_r*$countries->CZ_r/1000+
                                    $link->IS_visit_r*$countries->IS_r/1000+
                                    $link->LU_visit_r*$countries->LU_r/1000+
                                    $link->GR_visit_r*$countries->GR_r/1000+
                                    $link->FR_visit_r*$countries->FR_r/1000+
                                    $link->SG_visit_r*$countries->SG_r/1000+
                                    $link->IL_visit_r*$countries->IL_r/1000+
                                    $link->JP_visit_r*$countries->JP_r/1000+
                                    $link->MY_visit_r*$countries->MY_r/1000+
                                    $link->NG_visit_r*$countries->NG_r/1000+
                                    $link->PT_visit_r*$countries->PT_r/1000+
                                    $link->IQ_visit_r*$countries->IQ_r/1000+
                                    $link->LV_visit_r*$countries->LV_r/1000+
                                    $link->PS_visit_r*$countries->PS_r/1000+
                                    $link->SI_visit_r*$countries->SI_r/1000+
                                    $link->RU_visit_r*$countries->RU_r/1000+
                                    $link->BG_visit_r*$countries->BG_r/1000+
                                    $link->RS_visit_r*$countries->RS_r/1000+
                                    $link->ME_visit_r*$countries->ME_r/1000+
                                    $link->TH_visit_r*$countries->TH_r/1000+
                                    $link->LK_visit_r*$countries->LK_r/1000+
                                    $link->MM_visit_r*$countries->MM_r/1000+
                                    $link->IT_visit_r*$countries->IT_r/1000+
                                    $link->JO_visit_r*$countries->JO_r/1000+
                                    $link->KE_visit_r*$countries->KE_r/1000+
                                    $link->IR_visit_r*$countries->IR_r/1000+
                                    $link->GH_visit_r*$countries->GH_r/1000+
                                    $link->PA_visit_r*$countries->PA_r/1000+
                                    $link->MO_visit_r*$countries->MO_r/1000+
                                    $link->KZ_visit_r*$countries->KZ_r/1000+
                                    $link->BD_visit_r*$countries->BD_r/1000+
                                    $link->EE_visit_r*$countries->EE_r/1000+
                                    $link->LT_visit_r*$countries->LT_r/1000+
                                    $link->GE_visit_r*$countries->GE_r/1000+
                                    $link->MX_visit_r*$countries->MX_r/1000+
                                    $link->IO_visit_r*$countries->IO_r/1000+
                                    $link->MD_visit_r*$countries->MD_r/1000+
                                    $link->TZ_visit_r*$countries->TZ_r/1000+
                                    $link->INDO_visit_r*$countries->INDO_r/1000+
                                    $link->CI_visit_r*$countries->CI_r/1000+
                                    $link->BR_visit_r*$countries->BR_r/1000+
                                    $link->BA_visit_r*$countries->BA_r/1000+
                                    $link->HN_visit_r*$countries->HN_r/1000+
                                    $link->IN_visit_r*$countries->IN_r/1000+
                                    $link->VN_visit_r*$countries->VN_r/1000+
                                    $link->TW_visit_r*$countries->TW_r/1000+
                                    $link->GT_visit_r*$countries->GT_r/1000+
                                    $link->CN_visit_r*$countries->CN_r/1000+
                                    $link->KH_visit_r*$countries->KH_r/1000+
                                    $link->AT_visit_r*$countries->AT_r/1000+
                                    $link->SK_visit_r*$countries->SK_r/1000+
                                    $link->AM_visit_r*$countries->AM_r/1000+
                                    $link->AL_visit_r*$countries->AL_r/1000+
                                    $link->MK_visit_r*$countries->MK_r/1000+
                                    $link->TM_visit_r*$countries->TM_r/1000+
                                    $link->LB_visit_r*$countries->LB_r/1000+
                                    $link->EC_visit_r*$countries->EC_r/1000+
                                    $link->PH_visit_r*$countries->PH_r/1000+
                                    $link->HU_visit_r*$countries->HU_r/1000+
                                    $link->EG_visit_r*$countries->EG_r/1000+
                                    $link->PK_visit_r*$countries->PK_r/1000+
                                    $link->CM_visit_r*$countries->CM_r/1000+
                                    $link->UA_visit_r*$countries->UA_r/1000+
                                    $link->BM_visit_r*$countries->BM_r/1000+
                                    $link->NC_visit_r*$countries->NC_r/1000+
                                    $link->LY_visit_r*$countries->LY_r/1000+
                                    $link->AR_visit_r*$countries->AR_r/1000+
                                    $link->HK_visit_r*$countries->HK_r/1000+
                                    $link->TR_visit_r*$countries->TR_r/1000+
                                    $link->DZ_visit_r*$countries->DZ_r/1000+
                                    $link->RO_visit_r*$countries->RO_r/1000+
                                    $link->BS_visit_r*$countries->BS_r/1000+
                                    $link->GL_visit_r*$countries->GL_r/1000+
                                    $link->ZW_visit_r*$countries->ZW_r/1000+
                                    $link->LR_visit_r*$countries->LR_r/1000+
                                    $link->MF_visit_r*$countries->MF_r/1000+
                                    $link->BT_visit_r*$countries->BT_r/1000+
                                    $link->GF_visit_r*$countries->GF_r/1000+
                                    $link->NP_visit_r*$countries->NP_r/1000+
                                    $link->AF_visit_r*$countries->AF_r/1000+
                                    $link->CU_visit_r*$countries->CU_r/1000+
                                    $link->SV_visit_r*$countries->SV_r/1000+
                                    $link->SM_visit_r*$countries->SM_r/1000+
                                    $link->others_visit_r*$countries->others_r/1000+
                                    $link->US_visit_mr*$countries->US_mr/1000+
                                    $link->CA_visit_mr*$countries->CA_mr/1000+
                                    $link->GB_visit_mr*$countries->GB_mr/1000+
                                    $link->AU_visit_mr*$countries->AU_mr/1000+
                                    $link->DE_visit_mr*$countries->DE_mr/1000+
                                    $link->NO_visit_mr*$countries->NO_mr/1000+
                                    $link->AE_visit_mr*$countries->AE_mr/1000+
                                    $link->SE_visit_mr*$countries->SE_mr/1000+
                                    $link->ZA_visit_mr*$countries->ZA_mr/1000+
                                    $link->FI_visit_mr*$countries->FI_mr/1000+
                                    $link->DK_visit_mr*$countries->DK_mr/1000+
                                    $link->NZ_visit_mr*$countries->NZ_mr/1000+
                                    $link->PL_visit_mr*$countries->PL_mr/1000+
                                    $link->IE_visit_mr*$countries->IE_mr/1000+
                                    $link->CH_visit_mr*$countries->CH_mr/1000+
                                    $link->KW_visit_mr*$countries->KW_mr/1000+
                                    $link->QA_visit_mr*$countries->QA_mr/1000+
                                    $link->SA_visit_mr*$countries->SA_mr/1000+
                                    $link->BE_visit_mr*$countries->BE_mr/1000+
                                    $link->ES_visit_mr*$countries->ES_mr/1000+
                                    $link->KR_visit_mr*$countries->KR_mr/1000+
                                    $link->OM_visit_mr*$countries->OM_mr/1000+
                                    $link->CY_visit_mr*$countries->CY_mr/1000+
                                    $link->NL_visit_mr*$countries->NL_mr/1000+
                                    $link->CZ_visit_mr*$countries->CZ_mr/1000+
                                    $link->IS_visit_mr*$countries->IS_mr/1000+
                                    $link->LU_visit_mr*$countries->LU_mr/1000+
                                    $link->GR_visit_mr*$countries->GR_mr/1000+
                                    $link->FR_visit_mr*$countries->FR_mr/1000+
                                    $link->SG_visit_mr*$countries->SG_mr/1000+
                                    $link->IL_visit_mr*$countries->IL_mr/1000+
                                    $link->JP_visit_mr*$countries->JP_mr/1000+
                                    $link->MY_visit_mr*$countries->MY_mr/1000+
                                    $link->NG_visit_mr*$countries->NG_mr/1000+
                                    $link->PT_visit_mr*$countries->PT_mr/1000+
                                    $link->IQ_visit_mr*$countries->IQ_mr/1000+
                                    $link->LV_visit_mr*$countries->LV_mr/1000+
                                    $link->PS_visit_mr*$countries->PS_mr/1000+
                                    $link->SI_visit_mr*$countries->SI_mr/1000+
                                    $link->RU_visit_mr*$countries->RU_mr/1000+
                                    $link->BG_visit_mr*$countries->BG_mr/1000+
                                    $link->RS_visit_mr*$countries->RS_mr/1000+
                                    $link->ME_visit_mr*$countries->ME_mr/1000+
                                    $link->TH_visit_mr*$countries->TH_mr/1000+
                                    $link->LK_visit_mr*$countries->LK_mr/1000+
                                    $link->MM_visit_mr*$countries->MM_mr/1000+
                                    $link->IT_visit_mr*$countries->IT_mr/1000+
                                    $link->JO_visit_mr*$countries->JO_mr/1000+
                                    $link->KE_visit_mr*$countries->KE_mr/1000+
                                    $link->IR_visit_mr*$countries->IR_mr/1000+
                                    $link->GH_visit_mr*$countries->GH_mr/1000+
                                    $link->PA_visit_mr*$countries->PA_mr/1000+
                                    $link->MO_visit_mr*$countries->MO_mr/1000+
                                    $link->KZ_visit_mr*$countries->KZ_mr/1000+
                                    $link->BD_visit_mr*$countries->BD_mr/1000+
                                    $link->EE_visit_mr*$countries->EE_mr/1000+
                                    $link->LT_visit_mr*$countries->LT_mr/1000+
                                    $link->GE_visit_mr*$countries->GE_mr/1000+
                                    $link->MX_visit_mr*$countries->MX_mr/1000+
                                    $link->IO_visit_mr*$countries->IO_mr/1000+
                                    $link->MD_visit_mr*$countries->MD_mr/1000+
                                    $link->TZ_visit_mr*$countries->TZ_mr/1000+
                                    $link->INDO_visit_mr*$countries->INDO_mr/1000+
                                    $link->CI_visit_mr*$countries->CI_mr/1000+
                                    $link->BR_visit_mr*$countries->BR_mr/1000+
                                    $link->BA_visit_mr*$countries->BA_mr/1000+
                                    $link->HN_visit_mr*$countries->HN_mr/1000+
                                    $link->IN_visit_mr*$countries->IN_mr/1000+
                                    $link->VN_visit_mr*$countries->VN_mr/1000+
                                    $link->TW_visit_mr*$countries->TW_mr/1000+
                                    $link->GT_visit_mr*$countries->GT_mr/1000+
                                    $link->CN_visit_mr*$countries->CN_mr/1000+
                                    $link->KH_visit_mr*$countries->KH_mr/1000+
                                    $link->AT_visit_mr*$countries->AT_mr/1000+
                                    $link->SK_visit_mr*$countries->SK_mr/1000+
                                    $link->AM_visit_mr*$countries->AM_mr/1000+
                                    $link->AL_visit_mr*$countries->AL_mr/1000+
                                    $link->MK_visit_mr*$countries->MK_mr/1000+
                                    $link->TM_visit_mr*$countries->TM_mr/1000+
                                    $link->LB_visit_mr*$countries->LB_mr/1000+
                                    $link->EC_visit_mr*$countries->EC_mr/1000+
                                    $link->PH_visit_mr*$countries->PH_mr/1000+
                                    $link->HU_visit_mr*$countries->HU_mr/1000+
                                    $link->EG_visit_mr*$countries->EG_mr/1000+
                                    $link->PK_visit_mr*$countries->PK_mr/1000+
                                    $link->CM_visit_mr*$countries->CM_mr/1000+
                                    $link->UA_visit_mr*$countries->UA_mr/1000+
                                    $link->BM_visit_mr*$countries->BM_mr/1000+
                                    $link->NC_visit_mr*$countries->NC_mr/1000+
                                    $link->LY_visit_mr*$countries->LY_mr/1000+
                                    $link->AR_visit_mr*$countries->AR_mr/1000+
                                    $link->HK_visit_mr*$countries->HK_mr/1000+
                                    $link->TR_visit_mr*$countries->TR_mr/1000+
                                    $link->DZ_visit_mr*$countries->DZ_mr/1000+
                                    $link->RO_visit_mr*$countries->RO_mr/1000+
                                    $link->BS_visit_mr*$countries->BS_mr/1000+
                                    $link->GL_visit_mr*$countries->GL_mr/1000+
                                    $link->ZW_visit_mr*$countries->ZW_mr/1000+
                                    $link->LR_visit_mr*$countries->LR_mr/1000+
                                    $link->MF_visit_mr*$countries->MF_mr/1000+
                                    $link->BT_visit_mr*$countries->BT_mr/1000+
                                    $link->GF_visit_mr*$countries->GF_mr/1000+
                                    $link->NP_visit_mr*$countries->NP_mr/1000+
                                    $link->AF_visit_mr*$countries->AF_mr/1000+
                                    $link->CU_visit_mr*$countries->CU_mr/1000+
                                    $link->SV_visit_mr*$countries->SV_mr/1000+
                                    $link->SM_visit_mr*$countries->SM_mr/1000+
                                    $link->others_visit_mr*$countries->others_mr}} $</td>
                                    <td><a class="" href="/{{$link->id}}/analysis"> <i class="fa fa-eye" aria-hidden="true"></i> </a> </td>
                                          <td>{{$link->created_at->diffForHumans()}}</td>


                                                <td> 
                                          {!! Form::open(['route'=>['delete.Link',$link->id],'method'=>'DELETE']) !!}
<button class="btn btn-danger" type="submit">Delete</button>  
{!! Form::close()!!}</td>
      </tr>
      @endforeach
      </tbody>
      </table>

      </div>
      <div class="center-align">


{{ $links->links('vendor.pagination.simple-default') }}

</div>
      <style>
      table{
            padding: 2%;

      }

table, th, td {
      border: 0.5px solid black;
}
</style>

      @endsection