{{$link->US_visit_mobile*$countries->US_m/1000+
      $link->CA_visit_mobile*$countries->CA_m/1000+
      $link->GB_visit_mobile*$countries->GB_m/1000+
      $link->AU_visit_mobile*$countries->AU_m/1000+
      $link->DE_visit_mobile*$countries->DE_m/1000+
      $link->NO_visit_mobile*$countries->NO_m/1000+
      $link->AE_visit_mobile*$countries->AE_m/1000+
      $link->SE_visit_mobile*$countries->SE_m/1000+
      $link->ZA_visit_mobile*$countries->ZA_m/1000+
      $link->FI_visit_mobile*$countries->FI_m/1000+
      $link->DK_visit_mobile*$countries->DK_m/1000+
      $link->NZ_visit_mobile*$countries->NZ_m/1000+
      $link->PL_visit_mobile*$countries->PL_m/1000+
      $link->IE_visit_mobile*$countries->IE_m/1000+
      $link->CH_visit_mobile*$countries->CH_m/1000+
      $link->KW_visit_mobile*$countries->KW_m/1000+
      $link->QA_visit_mobile*$countries->QA_m/1000+
      $link->SA_visit_mobile*$countries->SA_m/1000+
      $link->BE_visit_mobile*$countries->BE_m/1000+
      $link->ES_visit_mobile*$countries->ES_m/1000+
      $link->KR_visit_mobile*$countries->KR_m/1000+
      $link->OM_visit_mobile*$countries->OM_m/1000+
      $link->CY_visit_mobile*$countries->CY_m/1000+
      $link->NL_visit_mobile*$countries->NL_m/1000+
      $link->CZ_visit_mobile*$countries->CZ_m/1000+
      $link->IS_visit_mobile*$countries->IS_m/1000+
      $link->LU_visit_mobile*$countries->LU_m/1000+
      $link->GR_visit_mobile*$countries->GR_m/1000+
      $link->FR_visit_mobile*$countries->FR_m/1000+
      $link->SG_visit_mobile*$countries->SG_m/1000+
      $link->IL_visit_mobile*$countries->IL_m/1000+
      $link->JP_visit_mobile*$countries->JP_m/1000+
      $link->MY_visit_mobile*$countries->MY_m/1000+
      $link->NG_visit_mobile*$countries->NG_m/1000+
      $link->PT_visit_mobile*$countries->PT_m/1000+
      $link->IQ_visit_mobile*$countries->IQ_m/1000+
      $link->LV_visit_mobile*$countries->LV_m/1000+
      $link->PS_visit_mobile*$countries->PS_m/1000+
      $link->SI_visit_mobile*$countries->SI_m/1000+
      $link->RU_visit_mobile*$countries->RU_m/1000+
      $link->BG_visit_mobile*$countries->BG_m/1000+
      $link->RS_visit_mobile*$countries->RS_m/1000+
      $link->ME_visit_mobile*$countries->ME_m/1000+
      $link->TH_visit_mobile*$countries->TH_m/1000+
      $link->LK_visit_mobile*$countries->LK_m/1000+
      $link->MM_visit_mobile*$countries->MM_m/1000+
      $link->IT_visit_mobile*$countries->IT_m/1000+
      $link->JO_visit_mobile*$countries->JO_m/1000+
      $link->KE_visit_mobile*$countries->KE_m/1000+
      $link->IR_visit_mobile*$countries->IR_m/1000+
      $link->GH_visit_mobile*$countries->GH_m/1000+
      $link->PA_visit_mobile*$countries->PA_m/1000+
      $link->MO_visit_mobile*$countries->MO_m/1000+
      $link->KZ_visit_mobile*$countries->KZ_m/1000+
      $link->BD_visit_mobile*$countries->BD_m/1000+
      $link->EE_visit_mobile*$countries->EE_m/1000+
      $link->LT_visit_mobile*$countries->LT_m/1000+
      $link->GE_visit_mobile*$countries->GE_m/1000+
      $link->MX_visit_mobile*$countries->MX_m/1000+
      $link->IO_visit_mobile*$countries->IO_m/1000+
      $link->MD_visit_mobile*$countries->MD_m/1000+
      $link->TZ_visit_mobile*$countries->TZ_m/1000+
      $link->INDO_visit_mobile*$countries->INDO_m/1000+
      $link->CI_visit_mobile*$countries->CI_m/1000+
      $link->BR_visit_mobile*$countries->BR_m/1000+
      $link->BA_visit_mobile*$countries->BA_m/1000+
      $link->HN_visit_mobile*$countries->HN_m/1000+
      $link->IN_visit_mobile*$countries->IN_m/1000+
      $link->VN_visit_mobile*$countries->VN_m/1000+
      $link->TW_visit_mobile*$countries->TW_m/1000+
      $link->GT_visit_mobile*$countries->GT_m/1000+
      $link->CN_visit_mobile*$countries->CN_m/1000+
      $link->KH_visit_mobile*$countries->KH_m/1000+
      $link->AT_visit_mobile*$countries->AT_m/1000+
      $link->SK_visit_mobile*$countries->SK_m/1000+
      $link->AM_visit_mobile*$countries->AM_m/1000+
      $link->AL_visit_mobile*$countries->AL_m/1000+
      $link->MK_visit_mobile*$countries->MK_m/1000+
      $link->TM_visit_mobile*$countries->TM_m/1000+
      $link->LB_visit_mobile*$countries->LB_m/1000+
      $link->EC_visit_mobile*$countries->EC_m/1000+
      $link->PH_visit_mobile*$countries->PH_m/1000+
      $link->HU_visit_mobile*$countries->HU_m/1000+
      $link->EG_visit_mobile*$countries->EG_m/1000+
      $link->PK_visit_mobile*$countries->PK_m/1000+
      $link->CM_visit_mobile*$countries->CM_m/1000+
      $link->UA_visit_mobile*$countries->UA_m/1000+
      $link->BM_visit_mobile*$countries->BM_m/1000+
      $link->NC_visit_mobile*$countries->NC_m/1000+
      $link->LY_visit_mobile*$countries->LY_m/1000+
      $link->AR_visit_mobile*$countries->AR_m/1000+
      $link->HK_visit_mobile*$countries->HK_m/1000+
      $link->TR_visit_mobile*$countries->TR_m/1000+
      $link->DZ_visit_mobile*$countries->DZ_m/1000+
      $link->RO_visit_mobile*$countries->RO_m/1000+
      $link->BS_visit_mobile*$countries->BS_m/1000+
      $link->GL_visit_mobile*$countries->GL_m/1000+
      $link->ZW_visit_mobile*$countries->ZW_m/1000+
      $link->LR_visit_mobile*$countries->LR_m/1000+
      $link->MF_visit_mobile*$countries->MF_m/1000+
      $link->BT_visit_mobile*$countries->BT_m/1000+
      $link->GF_visit_mobile*$countries->GF_m/1000+
      $link->NP_visit_mobile*$countries->NP_m/1000+
      $link->AF_visit_mobile*$countries->AF_m/1000+
      $link->CU_visit_mobile*$countries->CU_m/1000+
      $link->SV_visit_mobile*$countries->SV_m/1000+
      $link->SM_visit_mobile*$countries->SM_m/1000+
      $link->others_visit_mobile*$countries->others_m/1000 }}