{{            $link->US_visit+
      $link->CA_visit+
      $link->GB_visit+
      $link->AU_visit+
      $link->DE_visit+
      $link->NO_visit+
      $link->AE_visit+
      $link->SE_visit+
      $link->ZA_visit+
      $link->FI_visit+
      $link->DK_visit+
      $link->NZ_visit+
      $link->PL_visit+
      $link->IE_visit+
      $link->CH_visit+
      $link->KW_visit+
      $link->QA_visit+
      $link->SA_visit+
      $link->BE_visit+
      $link->ES_visit+
      $link->KR_visit+
      $link->OM_visit+
      $link->CY_visit+
      $link->NL_visit+
      $link->CZ_visit+
      $link->IS_visit+
      $link->LU_visit+
      $link->GR_visit+
      $link->FR_visit+
      $link->SG_visit+
      $link->IL_visit+
      $link->JP_visit+
      $link->MY_visit+
      $link->NG_visit+
      $link->PT_visit+
      $link->IQ_visit+
      $link->LV_visit+
      $link->PS_visit+
      $link->SI_visit+
      $link->RU_visit+
      $link->BG_visit+
      $link->RS_visit+
      $link->ME_visit+
      $link->TH_visit+
      $link->LK_visit+
      $link->MM_visit+
      $link->IT_visit+
      $link->JO_visit+
      $link->KE_visit+
      $link->IR_visit+
      $link->GH_visit+
      $link->PA_visit+
      $link->MO_visit+
      $link->KZ_visit+
      $link->BD_visit+
      $link->EE_visit+
      $link->LT_visit+
      $link->GE_visit+
      $link->MX_visit+
      $link->IO_visit+
      $link->MD_visit+
      $link->TZ_visit+
      $link->INDO_visit+
      $link->CI_visit+
      $link->BR_visit+
      $link->BA_visit+
      $link->HN_visit+
      $link->IN_visit+
      $link->VN_visit+
      $link->TW_visit+
      $link->GT_visit+
      $link->CN_visit+
      $link->KH_visit+
      $link->AT_visit+
      $link->SK_visit+
      $link->AM_visit+
      $link->AL_visit+
      $link->MK_visit+
      $link->TM_visit+
      $link->LB_visit+
      $link->EC_visit+
      $link->PH_visit+
      $link->HU_visit+
      $link->EG_visit+
      $link->PK_visit+
      $link->CM_visit+
      $link->UA_visit+
      $link->BM_visit+
      $link->NC_visit+
      $link->LY_visit+
      $link->AR_visit+
      $link->HK_visit+
      $link->TR_visit+
      $link->DZ_visit+
      $link->RO_visit+
      $link->BS_visit+
      $link->GL_visit+
      $link->ZW_visit+
      $link->LR_visit+
      $link->MF_visit+
      $link->BT_visit+
      $link->GF_visit+
      $link->NP_visit+
      $link->AF_visit+
      $link->CU_visit+
      $link->SV_visit+
      $link->SM_visit+
      $link->others_visit }}