{{ $link->US_visit_mobile+
      $link->CA_visit_mobile+
      $link->GB_visit_mobile+
      $link->AU_visit_mobile+
      $link->DE_visit_mobile+
      $link->NO_visit_mobile+
      $link->AE_visit_mobile+
      $link->SE_visit_mobile+
      $link->ZA_visit_mobile+
      $link->FI_visit_mobile+
      $link->DK_visit_mobile+
      $link->NZ_visit_mobile+
      $link->PL_visit_mobile+
      $link->IE_visit_mobile+
      $link->CH_visit_mobile+
      $link->KW_visit_mobile+
      $link->QA_visit_mobile+
      $link->SA_visit_mobile+
      $link->BE_visit_mobile+
      $link->ES_visit_mobile+
      $link->KR_visit_mobile+
      $link->OM_visit_mobile+
      $link->CY_visit_mobile+
      $link->NL_visit_mobile+
      $link->CZ_visit_mobile+
      $link->IS_visit_mobile+
      $link->LU_visit_mobile+
      $link->GR_visit_mobile+
      $link->FR_visit_mobile+
      $link->SG_visit_mobile+
      $link->IL_visit_mobile+
      $link->JP_visit_mobile+
      $link->MY_visit_mobile+
      $link->NG_visit_mobile+
      $link->PT_visit_mobile+
      $link->IQ_visit_mobile+
      $link->LV_visit_mobile+
      $link->PS_visit_mobile+
      $link->SI_visit_mobile+
      $link->RU_visit_mobile+
      $link->BG_visit_mobile+
      $link->RS_visit_mobile+
      $link->ME_visit_mobile+
      $link->TH_visit_mobile+
      $link->LK_visit_mobile+
      $link->MM_visit_mobile+
      $link->IT_visit_mobile+
      $link->JO_visit_mobile+
      $link->KE_visit_mobile+
      $link->IR_visit_mobile+
      $link->GH_visit_mobile+
      $link->PA_visit_mobile+
      $link->MO_visit_mobile+
      $link->KZ_visit_mobile+
      $link->BD_visit_mobile+
      $link->EE_visit_mobile+
      $link->LT_visit_mobile+
      $link->GE_visit_mobile+
      $link->MX_visit_mobile+
      $link->IO_visit_mobile+
      $link->MD_visit_mobile+
      $link->TZ_visit_mobile+
      $link->INDO_visit_mobile+
      $link->CI_visit_mobile+
      $link->BR_visit_mobile+
      $link->BA_visit_mobile+
      $link->HN_visit_mobile+
      $link->IN_visit_mobile+
      $link->VN_visit_mobile+
      $link->TW_visit_mobile+
      $link->GT_visit_mobile+
      $link->CN_visit_mobile+
      $link->KH_visit_mobile+
      $link->AT_visit_mobile+
      $link->SK_visit_mobile+
      $link->AM_visit_mobile+
      $link->AL_visit_mobile+
      $link->MK_visit_mobile+
      $link->TM_visit_mobile+
      $link->LB_visit_mobile+
      $link->EC_visit_mobile+
      $link->PH_visit_mobile+
      $link->HU_visit_mobile+
      $link->EG_visit_mobile+
      $link->PK_visit_mobile+
      $link->CM_visit_mobile+
      $link->UA_visit_mobile+
      $link->BM_visit_mobile+
      $link->NC_visit_mobile+
      $link->LY_visit_mobile+
      $link->AR_visit_mobile+
      $link->HK_visit_mobile+
      $link->TR_visit_mobile+
      $link->DZ_visit_mobile+
      $link->RO_visit_mobile+
      $link->BS_visit_mobile+
      $link->GL_visit_mobile+
      $link->ZW_visit_mobile+
      $link->LR_visit_mobile+
      $link->MF_visit_mobile+
      $link->BT_visit_mobile+
      $link->GF_visit_mobile+
      $link->NP_visit_mobile+
      $link->AF_visit_mobile+
      $link->CU_visit_mobile+
      $link->SV_visit_mobile+
      $link->SM_visit_mobile+
      $link->others_visit_mobile }}