{{$link->US_visit*$countries->US/1000+         
      $link->CA_visit*$countries->CA/1000+
      $link->GB_visit*$countries->GB/1000+
      $link->AU_visit*$countries->AU/1000+
      $link->DE_visit*$countries->DE/1000+
      $link->NO_visit*$countries->NO/1000+
      $link->AE_visit*$countries->AE/1000+
      $link->SE_visit*$countries->SE/1000+
      $link->ZA_visit*$countries->ZA/1000+
      $link->FI_visit*$countries->FI/1000+
      $link->DK_visit*$countries->DK/1000+
      $link->NZ_visit*$countries->NZ/1000+
      $link->PL_visit*$countries->PL/1000+
      $link->IE_visit*$countries->IE/1000+
      $link->CH_visit*$countries->CH/1000+
      $link->KW_visit*$countries->KW/1000+
      $link->QA_visit*$countries->QA/1000+
      $link->SA_visit*$countries->SA/1000+
      $link->BE_visit*$countries->BE/1000+
      $link->ES_visit*$countries->ES/1000+
      $link->KR_visit*$countries->KR/1000+
      $link->OM_visit*$countries->OM/1000+
      $link->CY_visit*$countries->CY/1000+
      $link->NL_visit*$countries->NL/1000+
      $link->CZ_visit*$countries->CZ/1000+
      $link->IS_visit*$countries->IS/1000+
      $link->LU_visit*$countries->LU/1000+
      $link->GR_visit*$countries->GR/1000+
      $link->FR_visit*$countries->FR/1000+
      $link->SG_visit*$countries->SG/1000+
      $link->IL_visit*$countries->IL/1000+
      $link->JP_visit*$countries->JP/1000+
      $link->MY_visit*$countries->MY/1000+
      $link->NG_visit*$countries->NG/1000+
      $link->PT_visit*$countries->PT/1000+
      $link->IQ_visit*$countries->IQ/1000+
      $link->LV_visit*$countries->LV/1000+
      $link->PS_visit*$countries->PS/1000+
      $link->SI_visit*$countries->SI/1000+
      $link->RU_visit*$countries->RU/1000+
      $link->BG_visit*$countries->BG/1000+
      $link->RS_visit*$countries->RS/1000+
      $link->ME_visit*$countries->ME/1000+
      $link->TH_visit*$countries->TH/1000+
      $link->LK_visit*$countries->LK/1000+
      $link->MM_visit*$countries->MM/1000+
      $link->IT_visit*$countries->IT/1000+
      $link->JO_visit*$countries->JO/1000+
      $link->KE_visit*$countries->KE/1000+
      $link->IR_visit*$countries->IR/1000+
      $link->GH_visit*$countries->GH/1000+
      $link->PA_visit*$countries->PA/1000+
      $link->MO_visit*$countries->MO/1000+
      $link->KZ_visit*$countries->KZ/1000+
      $link->BD_visit*$countries->BD/1000+
      $link->EE_visit*$countries->EE/1000+
      $link->LT_visit*$countries->LT/1000+
      $link->GE_visit*$countries->GE/1000+
      $link->MX_visit*$countries->MX/1000+
      $link->IO_visit*$countries->IO/1000+
      $link->MD_visit*$countries->MD/1000+
      $link->TZ_visit*$countries->TZ/1000+
      $link->INDO_visit*$countries->INDO/1000+
      $link->CI_visit*$countries->CI/1000+
      $link->BR_visit*$countries->BR/1000+
      $link->BA_visit*$countries->BA/1000+
      $link->HN_visit*$countries->HN/1000+
      $link->IN_visit*$countries->IN/1000+
      $link->VN_visit*$countries->VN/1000+
      $link->TW_visit*$countries->TW/1000+
      $link->GT_visit*$countries->GT/1000+
      $link->CN_visit*$countries->CN/1000+
      $link->KH_visit*$countries->KH/1000+
      $link->AT_visit*$countries->AT/1000+
      $link->SK_visit*$countries->SK/1000+
      $link->AM_visit*$countries->AM/1000+
      $link->AL_visit*$countries->AL/1000+
      $link->MK_visit*$countries->MK/1000+
      $link->TM_visit*$countries->TM/1000+
      $link->LB_visit*$countries->LB/1000+
      $link->EC_visit*$countries->EC/1000+
      $link->PH_visit*$countries->PH/1000+
      $link->HU_visit*$countries->HU/1000+
      $link->EG_visit*$countries->EG/1000+
      $link->PK_visit*$countries->PK/1000+
      $link->CM_visit*$countries->CM/1000+
      $link->UA_visit*$countries->UA/1000+
      $link->BM_visit*$countries->BM/1000+
      $link->NC_visit*$countries->NC/1000+
      $link->LY_visit*$countries->LY/1000+
      $link->AR_visit*$countries->AR/1000+
      $link->HK_visit*$countries->HK/1000+
      $link->TR_visit*$countries->TR/1000+
      $link->DZ_visit*$countries->DZ/1000+
      $link->RO_visit*$countries->RO/1000+
      $link->BS_visit*$countries->BS/1000+
      $link->GL_visit*$countries->GL/1000+
      $link->ZW_visit*$countries->ZW/1000+
      $link->LR_visit*$countries->LR/1000+
      $link->MF_visit*$countries->MF/1000+
      $link->BT_visit*$countries->BT/1000+
      $link->GF_visit*$countries->GF/1000+
      $link->NP_visit*$countries->NP/1000+
      $link->AF_visit*$countries->AF/1000+
      $link->CU_visit*$countries->CU/1000+
      $link->SV_visit*$countries->SV/1000+
      $link->SM_visit*$countries->SM/1000+
      $link->others_visit*$countries->others/1000 }}