{{$link->US_visit_r+
      $link->CA_visit_r+
      $link->GB_visit_r+
      $link->AU_visit_r+
      $link->DE_visit_r+
      $link->NO_visit_r+
      $link->AE_visit_r+
      $link->SE_visit_r+
      $link->ZA_visit_r+
      $link->FI_visit_r+
      $link->DK_visit_r+
      $link->NZ_visit_r+
      $link->PL_visit_r+
      $link->IE_visit_r+
      $link->CH_visit_r+
      $link->KW_visit_r+
      $link->QA_visit_r+
      $link->SA_visit_r+
      $link->BE_visit_r+
      $link->ES_visit_r+
      $link->KR_visit_r+
      $link->OM_visit_r+
      $link->CY_visit_r+
      $link->NL_visit_r+
      $link->CZ_visit_r+
      $link->IS_visit_r+
      $link->LU_visit_r+
      $link->GR_visit_r+
      $link->FR_visit_r+
      $link->SG_visit_r+
      $link->IL_visit_r+
      $link->JP_visit_r+
      $link->MY_visit_r+
      $link->NG_visit_r+
      $link->PT_visit_r+
      $link->IQ_visit_r+
      $link->LV_visit_r+
      $link->PS_visit_r+
      $link->SI_visit_r+
      $link->RU_visit_r+
      $link->BG_visit_r+
      $link->RS_visit_r+
      $link->ME_visit_r+
      $link->TH_visit_r+
      $link->LK_visit_r+
      $link->MM_visit_r+
      $link->IT_visit_r+
      $link->JO_visit_r+
      $link->KE_visit_r+
      $link->IR_visit_r+
      $link->GH_visit_r+
      $link->PA_visit_r+
      $link->MO_visit_r+
      $link->KZ_visit_r+
      $link->BD_visit_r+
      $link->EE_visit_r+
      $link->LT_visit_r+
      $link->GE_visit_r+
      $link->MX_visit_r+
      $link->IO_visit_r+
      $link->MD_visit_r+
      $link->TZ_visit_r+
      $link->INDO_visit_r+
      $link->CI_visit_r+
      $link->BR_visit_r+
      $link->BA_visit_r+
      $link->HN_visit_r+
      $link->IN_visit_r+
      $link->VN_visit_r+
      $link->TW_visit_r+
      $link->GT_visit_r+
      $link->CN_visit_r+
      $link->KH_visit_r+
      $link->AT_visit_r+
      $link->SK_visit_r+
      $link->AM_visit_r+
      $link->AL_visit_r+
      $link->MK_visit_r+
      $link->TM_visit_r+
      $link->LB_visit_r+
      $link->EC_visit_r+
      $link->PH_visit_r+
      $link->HU_visit_r+
      $link->EG_visit_r+
      $link->PK_visit_r+
      $link->CM_visit_r+
      $link->UA_visit_r+
      $link->BM_visit_r+
      $link->NC_visit_r+
      $link->LY_visit_r+
      $link->AR_visit_r+
      $link->HK_visit_r+
      $link->TR_visit_r+
      $link->DZ_visit_r+
      $link->RO_visit_r+
      $link->BS_visit_r+
      $link->GL_visit_r+
      $link->ZW_visit_r+
      $link->LR_visit_r+
      $link->MF_visit_r+
      $link->BT_visit_r+
      $link->GF_visit_r+
      $link->NP_visit_r+
      $link->AF_visit_r+
      $link->CU_visit_r+
      $link->SV_visit_r+
      $link->SM_visit_r+
      $link->others_visit_r }}