{{$link->US_visit_r*$countries->US_r/1000+
      $link->CA_visit_r*$countries->CA_r/1000+
      $link->GB_visit_r*$countries->GB_r/1000+
      $link->AU_visit_r*$countries->AU_r/1000+
      $link->DE_visit_r*$countries->DE_r/1000+
      $link->NO_visit_r*$countries->NO_r/1000+
      $link->AE_visit_r*$countries->AE_r/1000+
      $link->SE_visit_r*$countries->SE_r/1000+
      $link->ZA_visit_r*$countries->ZA_r/1000+
      $link->FI_visit_r*$countries->FI_r/1000+
      $link->DK_visit_r*$countries->DK_r/1000+
      $link->NZ_visit_r*$countries->NZ_r/1000+
      $link->PL_visit_r*$countries->PL_r/1000+
      $link->IE_visit_r*$countries->IE_r/1000+
      $link->CH_visit_r*$countries->CH_r/1000+
      $link->KW_visit_r*$countries->KW_r/1000+
      $link->QA_visit_r*$countries->QA_r/1000+
      $link->SA_visit_r*$countries->SA_r/1000+
      $link->BE_visit_r*$countries->BE_r/1000+
      $link->ES_visit_r*$countries->ES_r/1000+
      $link->KR_visit_r*$countries->KR_r/1000+
      $link->OM_visit_r*$countries->OM_r/1000+
      $link->CY_visit_r*$countries->CY_r/1000+
      $link->NL_visit_r*$countries->NL_r/1000+
      $link->CZ_visit_r*$countries->CZ_r/1000+
      $link->IS_visit_r*$countries->IS_r/1000+
      $link->LU_visit_r*$countries->LU_r/1000+
      $link->GR_visit_r*$countries->GR_r/1000+
      $link->FR_visit_r*$countries->FR_r/1000+
      $link->SG_visit_r*$countries->SG_r/1000+
      $link->IL_visit_r*$countries->IL_r/1000+
      $link->JP_visit_r*$countries->JP_r/1000+
      $link->MY_visit_r*$countries->MY_r/1000+
      $link->NG_visit_r*$countries->NG_r/1000+
      $link->PT_visit_r*$countries->PT_r/1000+
      $link->IQ_visit_r*$countries->IQ_r/1000+
      $link->LV_visit_r*$countries->LV_r/1000+
      $link->PS_visit_r*$countries->PS_r/1000+
      $link->SI_visit_r*$countries->SI_r/1000+
      $link->RU_visit_r*$countries->RU_r/1000+
      $link->BG_visit_r*$countries->BG_r/1000+
      $link->RS_visit_r*$countries->RS_r/1000+
      $link->ME_visit_r*$countries->ME_r/1000+
      $link->TH_visit_r*$countries->TH_r/1000+
      $link->LK_visit_r*$countries->LK_r/1000+
      $link->MM_visit_r*$countries->MM_r/1000+
      $link->IT_visit_r*$countries->IT_r/1000+
      $link->JO_visit_r*$countries->JO_r/1000+
      $link->KE_visit_r*$countries->KE_r/1000+
      $link->IR_visit_r*$countries->IR_r/1000+
      $link->GH_visit_r*$countries->GH_r/1000+
      $link->PA_visit_r*$countries->PA_r/1000+
      $link->MO_visit_r*$countries->MO_r/1000+
      $link->KZ_visit_r*$countries->KZ_r/1000+
      $link->BD_visit_r*$countries->BD_r/1000+
      $link->EE_visit_r*$countries->EE_r/1000+
      $link->LT_visit_r*$countries->LT_r/1000+
      $link->GE_visit_r*$countries->GE_r/1000+
      $link->MX_visit_r*$countries->MX_r/1000+
      $link->IO_visit_r*$countries->IO_r/1000+
      $link->MD_visit_r*$countries->MD_r/1000+
      $link->TZ_visit_r*$countries->TZ_r/1000+
      $link->INDO_visit_r*$countries->INDO_r/1000+
      $link->CI_visit_r*$countries->CI_r/1000+
      $link->BR_visit_r*$countries->BR_r/1000+
      $link->BA_visit_r*$countries->BA_r/1000+
      $link->HN_visit_r*$countries->HN_r/1000+
      $link->IN_visit_r*$countries->IN_r/1000+
      $link->VN_visit_r*$countries->VN_r/1000+
      $link->TW_visit_r*$countries->TW_r/1000+
      $link->GT_visit_r*$countries->GT_r/1000+
      $link->CN_visit_r*$countries->CN_r/1000+
      $link->KH_visit_r*$countries->KH_r/1000+
      $link->AT_visit_r*$countries->AT_r/1000+
      $link->SK_visit_r*$countries->SK_r/1000+
      $link->AM_visit_r*$countries->AM_r/1000+
      $link->AL_visit_r*$countries->AL_r/1000+
      $link->MK_visit_r*$countries->MK_r/1000+
      $link->TM_visit_r*$countries->TM_r/1000+
      $link->LB_visit_r*$countries->LB_r/1000+
      $link->EC_visit_r*$countries->EC_r/1000+
      $link->PH_visit_r*$countries->PH_r/1000+
      $link->HU_visit_r*$countries->HU_r/1000+
      $link->EG_visit_r*$countries->EG_r/1000+
      $link->PK_visit_r*$countries->PK_r/1000+
      $link->CM_visit_r*$countries->CM_r/1000+
      $link->UA_visit_r*$countries->UA_r/1000+
      $link->BM_visit_r*$countries->BM_r/1000+
      $link->NC_visit_r*$countries->NC_r/1000+
      $link->LY_visit_r*$countries->LY_r/1000+
      $link->AR_visit_r*$countries->AR_r/1000+
      $link->HK_visit_r*$countries->HK_r/1000+
      $link->TR_visit_r*$countries->TR_r/1000+
      $link->DZ_visit_r*$countries->DZ_r/1000+
      $link->RO_visit_r*$countries->RO_r/1000+
      $link->BS_visit_r*$countries->BS_r/1000+
      $link->GL_visit_r*$countries->GL_r/1000+
      $link->ZW_visit_r*$countries->ZW_r/1000+
      $link->LR_visit_r*$countries->LR_r/1000+
      $link->MF_visit_r*$countries->MF_r/1000+
      $link->BT_visit_r*$countries->BT_r/1000+
      $link->GF_visit_r*$countries->GF_r/1000+
      $link->NP_visit_r*$countries->NP_r/1000+
      $link->AF_visit_r*$countries->AF_r/1000+
      $link->CU_visit_r*$countries->CU_r/1000+
      $link->SV_visit_r*$countries->SV_r/1000+
      $link->SM_visit_r*$countries->SM_r/1000+
      $link->others_visit_r*$countries->others_r/1000 }}