{{$link->US_visit_mr+
      $link->CA_visit_mr+
      $link->GB_visit_mr+
      $link->AU_visit_mr+
      $link->DE_visit_mr+
      $link->NO_visit_mr+
      $link->AE_visit_mr+
      $link->SE_visit_mr+
      $link->ZA_visit_mr+
      $link->FI_visit_mr+
      $link->DK_visit_mr+
      $link->NZ_visit_mr+
      $link->PL_visit_mr+
      $link->IE_visit_mr+
      $link->CH_visit_mr+
      $link->KW_visit_mr+
      $link->QA_visit_mr+
      $link->SA_visit_mr+
      $link->BE_visit_mr+
      $link->ES_visit_mr+
      $link->KR_visit_mr+
      $link->OM_visit_mr+
      $link->CY_visit_mr+
      $link->NL_visit_mr+
      $link->CZ_visit_mr+
      $link->IS_visit_mr+
      $link->LU_visit_mr+
      $link->GR_visit_mr+
      $link->FR_visit_mr+
      $link->SG_visit_mr+
      $link->IL_visit_mr+
      $link->JP_visit_mr+
      $link->MY_visit_mr+
      $link->NG_visit_mr+
      $link->PT_visit_mr+
      $link->IQ_visit_mr+
      $link->LV_visit_mr+
      $link->PS_visit_mr+
      $link->SI_visit_mr+
      $link->RU_visit_mr+
      $link->BG_visit_mr+
      $link->RS_visit_mr+
      $link->ME_visit_mr+
      $link->TH_visit_mr+
      $link->LK_visit_mr+
      $link->MM_visit_mr+
      $link->IT_visit_mr+
      $link->JO_visit_mr+
      $link->KE_visit_mr+
      $link->IR_visit_mr+
      $link->GH_visit_mr+
      $link->PA_visit_mr+
      $link->MO_visit_mr+
      $link->KZ_visit_mr+
      $link->BD_visit_mr+
      $link->EE_visit_mr+
      $link->LT_visit_mr+
      $link->GE_visit_mr+
      $link->MX_visit_mr+
      $link->IO_visit_mr+
      $link->MD_visit_mr+
      $link->TZ_visit_mr+
      $link->INDO_visit_mr+
      $link->CI_visit_mr+
      $link->BR_visit_mr+
      $link->BA_visit_mr+
      $link->HN_visit_mr+
      $link->IN_visit_mr+
      $link->VN_visit_mr+
      $link->TW_visit_mr+
      $link->GT_visit_mr+
      $link->CN_visit_mr+
      $link->KH_visit_mr+
      $link->AT_visit_mr+
      $link->SK_visit_mr+
      $link->AM_visit_mr+
      $link->AL_visit_mr+
      $link->MK_visit_mr+
      $link->TM_visit_mr+
      $link->LB_visit_mr+
      $link->EC_visit_mr+
      $link->PH_visit_mr+
      $link->HU_visit_mr+
      $link->EG_visit_mr+
      $link->PK_visit_mr+
      $link->CM_visit_mr+
      $link->UA_visit_mr+
      $link->BM_visit_mr+
      $link->NC_visit_mr+
      $link->LY_visit_mr+
      $link->AR_visit_mr+
      $link->HK_visit_mr+
      $link->TR_visit_mr+
      $link->DZ_visit_mr+
      $link->RO_visit_mr+
      $link->BS_visit_mr+
      $link->GL_visit_mr+
      $link->ZW_visit_mr+
      $link->LR_visit_mr+
      $link->MF_visit_mr+
      $link->BT_visit_mr+
      $link->GF_visit_mr+
      $link->NP_visit_mr+
      $link->AF_visit_mr+
      $link->CU_visit_mr+
      $link->SV_visit_mr+
      $link->SM_visit_mr+
      $link->others_visit_mr}}