{{$link->US_visit_mr*$countries->US_mr/1000+
      $link->CA_visit_mr*$countries->CA_mr/1000+
      $link->GB_visit_mr*$countries->GB_mr/1000+
      $link->AU_visit_mr*$countries->AU_mr/1000+
      $link->DE_visit_mr*$countries->DE_mr/1000+
      $link->NO_visit_mr*$countries->NO_mr/1000+
      $link->AE_visit_mr*$countries->AE_mr/1000+
      $link->SE_visit_mr*$countries->SE_mr/1000+
      $link->ZA_visit_mr*$countries->ZA_mr/1000+
      $link->FI_visit_mr*$countries->FI_mr/1000+
      $link->DK_visit_mr*$countries->DK_mr/1000+
      $link->NZ_visit_mr*$countries->NZ_mr/1000+
      $link->PL_visit_mr*$countries->PL_mr/1000+
      $link->IE_visit_mr*$countries->IE_mr/1000+
      $link->CH_visit_mr*$countries->CH_mr/1000+
      $link->KW_visit_mr*$countries->KW_mr/1000+
      $link->QA_visit_mr*$countries->QA_mr/1000+
      $link->SA_visit_mr*$countries->SA_mr/1000+
      $link->BE_visit_mr*$countries->BE_mr/1000+
      $link->ES_visit_mr*$countries->ES_mr/1000+
      $link->KR_visit_mr*$countries->KR_mr/1000+
      $link->OM_visit_mr*$countries->OM_mr/1000+
      $link->CY_visit_mr*$countries->CY_mr/1000+
      $link->NL_visit_mr*$countries->NL_mr/1000+
      $link->CZ_visit_mr*$countries->CZ_mr/1000+
      $link->IS_visit_mr*$countries->IS_mr/1000+
      $link->LU_visit_mr*$countries->LU_mr/1000+
      $link->GR_visit_mr*$countries->GR_mr/1000+
      $link->FR_visit_mr*$countries->FR_mr/1000+
      $link->SG_visit_mr*$countries->SG_mr/1000+
      $link->IL_visit_mr*$countries->IL_mr/1000+
      $link->JP_visit_mr*$countries->JP_mr/1000+
      $link->MY_visit_mr*$countries->MY_mr/1000+
      $link->NG_visit_mr*$countries->NG_mr/1000+
      $link->PT_visit_mr*$countries->PT_mr/1000+
      $link->IQ_visit_mr*$countries->IQ_mr/1000+
      $link->LV_visit_mr*$countries->LV_mr/1000+
      $link->PS_visit_mr*$countries->PS_mr/1000+
      $link->SI_visit_mr*$countries->SI_mr/1000+
      $link->RU_visit_mr*$countries->RU_mr/1000+
      $link->BG_visit_mr*$countries->BG_mr/1000+
      $link->RS_visit_mr*$countries->RS_mr/1000+
      $link->ME_visit_mr*$countries->ME_mr/1000+
      $link->TH_visit_mr*$countries->TH_mr/1000+
      $link->LK_visit_mr*$countries->LK_mr/1000+
      $link->MM_visit_mr*$countries->MM_mr/1000+
      $link->IT_visit_mr*$countries->IT_mr/1000+
      $link->JO_visit_mr*$countries->JO_mr/1000+
      $link->KE_visit_mr*$countries->KE_mr/1000+
      $link->IR_visit_mr*$countries->IR_mr/1000+
      $link->GH_visit_mr*$countries->GH_mr/1000+
      $link->PA_visit_mr*$countries->PA_mr/1000+
      $link->MO_visit_mr*$countries->MO_mr/1000+
      $link->KZ_visit_mr*$countries->KZ_mr/1000+
      $link->BD_visit_mr*$countries->BD_mr/1000+
      $link->EE_visit_mr*$countries->EE_mr/1000+
      $link->LT_visit_mr*$countries->LT_mr/1000+
      $link->GE_visit_mr*$countries->GE_mr/1000+
      $link->MX_visit_mr*$countries->MX_mr/1000+
      $link->IO_visit_mr*$countries->IO_mr/1000+
      $link->MD_visit_mr*$countries->MD_mr/1000+
      $link->TZ_visit_mr*$countries->TZ_mr/1000+
      $link->INDO_visit_mr*$countries->INDO_mr/1000+
      $link->CI_visit_mr*$countries->CI_mr/1000+
      $link->BR_visit_mr*$countries->BR_mr/1000+
      $link->BA_visit_mr*$countries->BA_mr/1000+
      $link->HN_visit_mr*$countries->HN_mr/1000+
      $link->IN_visit_mr*$countries->IN_mr/1000+
      $link->VN_visit_mr*$countries->VN_mr/1000+
      $link->TW_visit_mr*$countries->TW_mr/1000+
      $link->GT_visit_mr*$countries->GT_mr/1000+
      $link->CN_visit_mr*$countries->CN_mr/1000+
      $link->KH_visit_mr*$countries->KH_mr/1000+
      $link->AT_visit_mr*$countries->AT_mr/1000+
      $link->SK_visit_mr*$countries->SK_mr/1000+
      $link->AM_visit_mr*$countries->AM_mr/1000+
      $link->AL_visit_mr*$countries->AL_mr/1000+
      $link->MK_visit_mr*$countries->MK_mr/1000+
      $link->TM_visit_mr*$countries->TM_mr/1000+
      $link->LB_visit_mr*$countries->LB_mr/1000+
      $link->EC_visit_mr*$countries->EC_mr/1000+
      $link->PH_visit_mr*$countries->PH_mr/1000+
      $link->HU_visit_mr*$countries->HU_mr/1000+
      $link->EG_visit_mr*$countries->EG_mr/1000+
      $link->PK_visit_mr*$countries->PK_mr/1000+
      $link->CM_visit_mr*$countries->CM_mr/1000+
      $link->UA_visit_mr*$countries->UA_mr/1000+
      $link->BM_visit_mr*$countries->BM_mr/1000+
      $link->NC_visit_mr*$countries->NC_mr/1000+
      $link->LY_visit_mr*$countries->LY_mr/1000+
      $link->AR_visit_mr*$countries->AR_mr/1000+
      $link->HK_visit_mr*$countries->HK_mr/1000+
      $link->TR_visit_mr*$countries->TR_mr/1000+
      $link->DZ_visit_mr*$countries->DZ_mr/1000+
      $link->RO_visit_mr*$countries->RO_mr/1000+
      $link->BS_visit_mr*$countries->BS_mr/1000+
      $link->GL_visit_mr*$countries->GL_mr/1000+
      $link->ZW_visit_mr*$countries->ZW_mr/1000+
      $link->LR_visit_mr*$countries->LR_mr/1000+
      $link->MF_visit_mr*$countries->MF_mr/1000+
      $link->BT_visit_mr*$countries->BT_mr/1000+
      $link->GF_visit_mr*$countries->GF_mr/1000+
      $link->NP_visit_mr*$countries->NP_mr/1000+
      $link->AF_visit_mr*$countries->AF_mr/1000+
      $link->CU_visit_mr*$countries->CU_mr/1000+
      $link->SV_visit_mr*$countries->SV_mr/1000+
      $link->SM_visit_mr*$countries->SM_mr/1000+
      $link->others_visit_mr*$countries->others_mr}}