{{            $link->US_visit+
      $link->CA_visit+
      $link->GB_visit+
      $link->AU_visit+
      $link->DE_visit+
      $link->NO_visit+
      $link->AE_visit+
      $link->SE_visit+
      $link->ZA_visit+
      $link->FI_visit+
      $link->DK_visit+
      $link->NZ_visit+
      $link->PL_visit+
      $link->IE_visit+
      $link->CH_visit+
      $link->KW_visit+
      $link->QA_visit+
      $link->SA_visit+
      $link->BE_visit+
      $link->ES_visit+
      $link->KR_visit+
      $link->OM_visit+
      $link->CY_visit+
      $link->NL_visit+
      $link->CZ_visit+
      $link->IS_visit+
      $link->LU_visit+
      $link->GR_visit+
      $link->FR_visit+
      $link->SG_visit+
      $link->IL_visit+
      $link->JP_visit+
      $link->MY_visit+
      $link->NG_visit+
      $link->PT_visit+
      $link->IQ_visit+
      $link->LV_visit+
      $link->PS_visit+
      $link->SI_visit+
      $link->RU_visit+
      $link->BG_visit+
      $link->RS_visit+
      $link->ME_visit+
      $link->TH_visit+
      $link->LK_visit+
      $link->MM_visit+
      $link->IT_visit+
      $link->JO_visit+
      $link->KE_visit+
      $link->IR_visit+
      $link->GH_visit+
      $link->PA_visit+
      $link->MO_visit+
      $link->KZ_visit+
      $link->BD_visit+
      $link->EE_visit+
      $link->LT_visit+
      $link->GE_visit+
      $link->MX_visit+
      $link->IO_visit+
      $link->MD_visit+
      $link->TZ_visit+
      $link->INDO_visit+
      $link->CI_visit+
      $link->BR_visit+
      $link->BA_visit+
      $link->HN_visit+
      $link->IN_visit+
      $link->VN_visit+
      $link->TW_visit+
      $link->GT_visit+
      $link->CN_visit+
      $link->KH_visit+
      $link->AT_visit+
      $link->SK_visit+
      $link->AM_visit+
      $link->AL_visit+
      $link->MK_visit+
      $link->TM_visit+
      $link->LB_visit+
      $link->EC_visit+
      $link->PH_visit+
      $link->HU_visit+
      $link->EG_visit+
      $link->PK_visit+
      $link->CM_visit+
      $link->UA_visit+
      $link->BM_visit+
      $link->NC_visit+
      $link->LY_visit+
      $link->AR_visit+
      $link->HK_visit+
      $link->TR_visit+
      $link->DZ_visit+
      $link->RO_visit+
      $link->BS_visit+
      $link->GL_visit+
      $link->ZW_visit+
      $link->LR_visit+
      $link->MF_visit+
      $link->BT_visit+
      $link->GF_visit+
      $link->NP_visit+
      $link->AF_visit+
      $link->CU_visit+
      $link->SV_visit+
      $link->SM_visit+
      $link->others_visit+


      $link->US_visit_mobile+
      $link->CA_visit_mobile+
      $link->GB_visit_mobile+
      $link->AU_visit_mobile+
      $link->DE_visit_mobile+
      $link->NO_visit_mobile+
      $link->AE_visit_mobile+
      $link->SE_visit_mobile+
      $link->ZA_visit_mobile+
      $link->FI_visit_mobile+
      $link->DK_visit_mobile+
      $link->NZ_visit_mobile+
      $link->PL_visit_mobile+
      $link->IE_visit_mobile+
      $link->CH_visit_mobile+
      $link->KW_visit_mobile+
      $link->QA_visit_mobile+
      $link->SA_visit_mobile+
      $link->BE_visit_mobile+
      $link->ES_visit_mobile+
      $link->KR_visit_mobile+
      $link->OM_visit_mobile+
      $link->CY_visit_mobile+
      $link->NL_visit_mobile+
      $link->CZ_visit_mobile+
      $link->IS_visit_mobile+
      $link->LU_visit_mobile+
      $link->GR_visit_mobile+
      $link->FR_visit_mobile+
      $link->SG_visit_mobile+
      $link->IL_visit_mobile+
      $link->JP_visit_mobile+
      $link->MY_visit_mobile+
      $link->NG_visit_mobile+
      $link->PT_visit_mobile+
      $link->IQ_visit_mobile+
      $link->LV_visit_mobile+
      $link->PS_visit_mobile+
      $link->SI_visit_mobile+
      $link->RU_visit_mobile+
      $link->BG_visit_mobile+
      $link->RS_visit_mobile+
      $link->ME_visit_mobile+
      $link->TH_visit_mobile+
      $link->LK_visit_mobile+
      $link->MM_visit_mobile+
      $link->IT_visit_mobile+
      $link->JO_visit_mobile+
      $link->KE_visit_mobile+
      $link->IR_visit_mobile+
      $link->GH_visit_mobile+
      $link->PA_visit_mobile+
      $link->MO_visit_mobile+
      $link->KZ_visit_mobile+
      $link->BD_visit_mobile+
      $link->EE_visit_mobile+
      $link->LT_visit_mobile+
      $link->GE_visit_mobile+
      $link->MX_visit_mobile+
      $link->IO_visit_mobile+
      $link->MD_visit_mobile+
      $link->TZ_visit_mobile+
      $link->INDO_visit_mobile+
      $link->CI_visit_mobile+
      $link->BR_visit_mobile+
      $link->BA_visit_mobile+
      $link->HN_visit_mobile+
      $link->IN_visit_mobile+
      $link->VN_visit_mobile+
      $link->TW_visit_mobile+
      $link->GT_visit_mobile+
      $link->CN_visit_mobile+
      $link->KH_visit_mobile+
      $link->AT_visit_mobile+
      $link->SK_visit_mobile+
      $link->AM_visit_mobile+
      $link->AL_visit_mobile+
      $link->MK_visit_mobile+
      $link->TM_visit_mobile+
      $link->LB_visit_mobile+
      $link->EC_visit_mobile+
      $link->PH_visit_mobile+
      $link->HU_visit_mobile+
      $link->EG_visit_mobile+
      $link->PK_visit_mobile+
      $link->CM_visit_mobile+
      $link->UA_visit_mobile+
      $link->BM_visit_mobile+
      $link->NC_visit_mobile+
      $link->LY_visit_mobile+
      $link->AR_visit_mobile+
      $link->HK_visit_mobile+
      $link->TR_visit_mobile+
      $link->DZ_visit_mobile+
      $link->RO_visit_mobile+
      $link->BS_visit_mobile+
      $link->GL_visit_mobile+
      $link->ZW_visit_mobile+
      $link->LR_visit_mobile+
      $link->MF_visit_mobile+
      $link->BT_visit_mobile+
      $link->GF_visit_mobile+
      $link->NP_visit_mobile+
      $link->AF_visit_mobile+
      $link->CU_visit_mobile+
      $link->SV_visit_mobile+
      $link->SM_visit_mobile+
      $link->others_visit_mobile+

      $link->US_visit_r+
      $link->CA_visit_r+
      $link->GB_visit_r+
      $link->AU_visit_r+
      $link->DE_visit_r+
      $link->NO_visit_r+
      $link->AE_visit_r+
      $link->SE_visit_r+
      $link->ZA_visit_r+
      $link->FI_visit_r+
      $link->DK_visit_r+
      $link->NZ_visit_r+
      $link->PL_visit_r+
      $link->IE_visit_r+
      $link->CH_visit_r+
      $link->KW_visit_r+
      $link->QA_visit_r+
      $link->SA_visit_r+
      $link->BE_visit_r+
      $link->ES_visit_r+
      $link->KR_visit_r+
      $link->OM_visit_r+
      $link->CY_visit_r+
      $link->NL_visit_r+
      $link->CZ_visit_r+
      $link->IS_visit_r+
      $link->LU_visit_r+
      $link->GR_visit_r+
      $link->FR_visit_r+
      $link->SG_visit_r+
      $link->IL_visit_r+
      $link->JP_visit_r+
      $link->MY_visit_r+
      $link->NG_visit_r+
      $link->PT_visit_r+
      $link->IQ_visit_r+
      $link->LV_visit_r+
      $link->PS_visit_r+
      $link->SI_visit_r+
      $link->RU_visit_r+
      $link->BG_visit_r+
      $link->RS_visit_r+
      $link->ME_visit_r+
      $link->TH_visit_r+
      $link->LK_visit_r+
      $link->MM_visit_r+
      $link->IT_visit_r+
      $link->JO_visit_r+
      $link->KE_visit_r+
      $link->IR_visit_r+
      $link->GH_visit_r+
      $link->PA_visit_r+
      $link->MO_visit_r+
      $link->KZ_visit_r+
      $link->BD_visit_r+
      $link->EE_visit_r+
      $link->LT_visit_r+
      $link->GE_visit_r+
      $link->MX_visit_r+
      $link->IO_visit_r+
      $link->MD_visit_r+
      $link->TZ_visit_r+
      $link->INDO_visit_r+
      $link->CI_visit_r+
      $link->BR_visit_r+
      $link->BA_visit_r+
      $link->HN_visit_r+
      $link->IN_visit_r+
      $link->VN_visit_r+
      $link->TW_visit_r+
      $link->GT_visit_r+
      $link->CN_visit_r+
      $link->KH_visit_r+
      $link->AT_visit_r+
      $link->SK_visit_r+
      $link->AM_visit_r+
      $link->AL_visit_r+
      $link->MK_visit_r+
      $link->TM_visit_r+
      $link->LB_visit_r+
      $link->EC_visit_r+
      $link->PH_visit_r+
      $link->HU_visit_r+
      $link->EG_visit_r+
      $link->PK_visit_r+
      $link->CM_visit_r+
      $link->UA_visit_r+
      $link->BM_visit_r+
      $link->NC_visit_r+
      $link->LY_visit_r+
      $link->AR_visit_r+
      $link->HK_visit_r+
      $link->TR_visit_r+
      $link->DZ_visit_r+
      $link->RO_visit_r+
      $link->BS_visit_r+
      $link->GL_visit_r+
      $link->ZW_visit_r+
      $link->LR_visit_r+
      $link->MF_visit_r+
      $link->BT_visit_r+
      $link->GF_visit_r+
      $link->NP_visit_r+
      $link->AF_visit_r+
      $link->CU_visit_r+
      $link->SV_visit_r+
      $link->SM_visit_r+
      $link->others_visit_r+

      $link->US_visit_mr+
      $link->CA_visit_mr+
      $link->GB_visit_mr+
      $link->AU_visit_mr+
      $link->DE_visit_mr+
      $link->NO_visit_mr+
      $link->AE_visit_mr+
      $link->SE_visit_mr+
      $link->ZA_visit_mr+
      $link->FI_visit_mr+
      $link->DK_visit_mr+
      $link->NZ_visit_mr+
      $link->PL_visit_mr+
      $link->IE_visit_mr+
      $link->CH_visit_mr+
      $link->KW_visit_mr+
      $link->QA_visit_mr+
      $link->SA_visit_mr+
      $link->BE_visit_mr+
      $link->ES_visit_mr+
      $link->KR_visit_mr+
      $link->OM_visit_mr+
      $link->CY_visit_mr+
      $link->NL_visit_mr+
      $link->CZ_visit_mr+
      $link->IS_visit_mr+
      $link->LU_visit_mr+
      $link->GR_visit_mr+
      $link->FR_visit_mr+
      $link->SG_visit_mr+
      $link->IL_visit_mr+
      $link->JP_visit_mr+
      $link->MY_visit_mr+
      $link->NG_visit_mr+
      $link->PT_visit_mr+
      $link->IQ_visit_mr+
      $link->LV_visit_mr+
      $link->PS_visit_mr+
      $link->SI_visit_mr+
      $link->RU_visit_mr+
      $link->BG_visit_mr+
      $link->RS_visit_mr+
      $link->ME_visit_mr+
      $link->TH_visit_mr+
      $link->LK_visit_mr+
      $link->MM_visit_mr+
      $link->IT_visit_mr+
      $link->JO_visit_mr+
      $link->KE_visit_mr+
      $link->IR_visit_mr+
      $link->GH_visit_mr+
      $link->PA_visit_mr+
      $link->MO_visit_mr+
      $link->KZ_visit_mr+
      $link->BD_visit_mr+
      $link->EE_visit_mr+
      $link->LT_visit_mr+
      $link->GE_visit_mr+
      $link->MX_visit_mr+
      $link->IO_visit_mr+
      $link->MD_visit_mr+
      $link->TZ_visit_mr+
      $link->INDO_visit_mr+
      $link->CI_visit_mr+
      $link->BR_visit_mr+
      $link->BA_visit_mr+
      $link->HN_visit_mr+
      $link->IN_visit_mr+
      $link->VN_visit_mr+
      $link->TW_visit_mr+
      $link->GT_visit_mr+
      $link->CN_visit_mr+
      $link->KH_visit_mr+
      $link->AT_visit_mr+
      $link->SK_visit_mr+
      $link->AM_visit_mr+
      $link->AL_visit_mr+
      $link->MK_visit_mr+
      $link->TM_visit_mr+
      $link->LB_visit_mr+
      $link->EC_visit_mr+
      $link->PH_visit_mr+
      $link->HU_visit_mr+
      $link->EG_visit_mr+
      $link->PK_visit_mr+
      $link->CM_visit_mr+
      $link->UA_visit_mr+
      $link->BM_visit_mr+
      $link->NC_visit_mr+
      $link->LY_visit_mr+
      $link->AR_visit_mr+
      $link->HK_visit_mr+
      $link->TR_visit_mr+
      $link->DZ_visit_mr+
      $link->RO_visit_mr+
      $link->BS_visit_mr+
      $link->GL_visit_mr+
      $link->ZW_visit_mr+
      $link->LR_visit_mr+
      $link->MF_visit_mr+
      $link->BT_visit_mr+
      $link->GF_visit_mr+
      $link->NP_visit_mr+
      $link->AF_visit_mr+
      $link->CU_visit_mr+
      $link->SV_visit_mr+
      $link->SM_visit_mr+
      $link->others_visit_mr}}