<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\country;


use Redirect;

class PayoutRates extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.crud.rates.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $country = country::all();
        if ($country->count() > 0) {
            $country = country::orderBy('created_at', 'desc')->first();
            return redirect()->action(
                'PayoutRates@edit', ['id' => $country->id]
            );
        } else {
            return view('admin.crud.rates.create');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'us_d_u'=>'required|numeric',
            'us_d_r'=>'required|numeric',
            'us_m_u'=>'required|numeric',
            'us_m_r'=>'required|numeric',
            'ca_d_u'=>'required|numeric',
            'ca_d_r'=>'required|numeric',
            'ca_m_u'=>'required|numeric',
            'ca_m_r'=>'required|numeric',
            'gb_d_u'=>'required|numeric',
            'gb_d_r'=>'required|numeric',
            'gb_m_u'=>'required|numeric',
            'gb_m_r'=>'required|numeric',
            'au_d_u'=>'required|numeric',
            'au_d_r'=>'required|numeric',
            'au_m_u'=>'required|numeric',
            'au_m_r'=>'required|numeric',
            'de_d_u'=>'required|numeric',
            'de_d_r'=>'required|numeric',
            'de_m_u'=>'required|numeric',
            'de_m_r'=>'required|numeric',
            'no_d_u'=>'required|numeric',
            'no_d_r'=>'required|numeric',
            'no_m_u'=>'required|numeric',
            'no_m_r'=>'required|numeric',
            'ae_d_u'=>'required|numeric',
            'ae_d_r'=>'required|numeric',
            'ae_m_u'=>'required|numeric',
            'ae_m_r'=>'required|numeric',
            'se_d_u'=>'required|numeric',
            'se_d_r'=>'required|numeric',
            'se_m_u'=>'required|numeric',
            'se_m_r'=>'required|numeric',
            'za_d_u'=>'required|numeric',
            'za_d_r'=>'required|numeric',
            'za_m_u'=>'required|numeric',
            'za_m_r'=>'required|numeric',
            'fi_d_u'=>'required|numeric',
            'fi_d_r'=>'required|numeric',
            'fi_m_u'=>'required|numeric',
            'fi_m_r'=>'required|numeric',
            'dk_d_u'=>'required|numeric',
            'dk_d_r'=>'required|numeric',
            'dk_m_u'=>'required|numeric',
            'dk_m_r'=>'required|numeric',
            'nz_d_u'=>'required|numeric',
            'nz_d_r'=>'required|numeric',
            'nz_m_u'=>'required|numeric',
            'nz_m_r'=>'required|numeric',
            'pl_d_u'=>'required|numeric',
            'pl_d_r'=>'required|numeric',
            'pl_m_u'=>'required|numeric',
            'pl_m_r'=>'required|numeric',
            'ie_d_u'=>'required|numeric',
            'ie_d_r'=>'required|numeric',
            'ie_m_u'=>'required|numeric',
            'ie_m_r'=>'required|numeric',
            'ch_d_u'=>'required|numeric',
            'ch_d_r'=>'required|numeric',
            'ch_m_u'=>'required|numeric',
            'ch_m_r'=>'required|numeric',
            'kw_d_u'=>'required|numeric',
            'kw_d_r'=>'required|numeric',
            'kw_m_u'=>'required|numeric',
            'kw_m_r'=>'required|numeric',
            'qa_d_u'=>'required|numeric',
            'qa_d_r'=>'required|numeric',
            'qa_m_u'=>'required|numeric',
            'qa_m_r'=>'required|numeric',
            'sa_d_u'=>'required|numeric',
            'sa_d_r'=>'required|numeric',
            'sa_m_u'=>'required|numeric',
            'sa_m_r'=>'required|numeric',
            'be_d_u'=>'required|numeric',
            'be_d_r'=>'required|numeric',
            'be_m_u'=>'required|numeric',
            'be_m_r'=>'required|numeric',
            'es_d_u'=>'required|numeric',
            'es_d_r'=>'required|numeric',
            'es_m_u'=>'required|numeric',
            'es_m_r'=>'required|numeric',
            'kr_d_u'=>'required|numeric',
            'kr_d_r'=>'required|numeric',
            'kr_m_u'=>'required|numeric',
            'kr_m_r'=>'required|numeric',
            'om_d_u'=>'required|numeric',
            'om_d_r'=>'required|numeric',
            'om_m_u'=>'required|numeric',
            'om_m_r'=>'required|numeric',
            'cy_d_u'=>'required|numeric',
            'cy_d_r'=>'required|numeric',
            'cy_m_u'=>'required|numeric',
            'cy_m_r'=>'required|numeric',
            'nl_d_u'=>'required|numeric',
            'nl_d_r'=>'required|numeric',
            'nl_m_u'=>'required|numeric',
            'nl_m_r'=>'required|numeric',
            'cz_d_u'=>'required|numeric',
            'cz_d_r'=>'required|numeric',
            'cz_m_u'=>'required|numeric',
            'cz_m_r'=>'required|numeric',
            'is_d_u'=>'required|numeric',
            'is_d_r'=>'required|numeric',
            'is_m_u'=>'required|numeric',
            'is_m_r'=>'required|numeric',
            'lu_d_u'=>'required|numeric',
            'lu_d_r'=>'required|numeric',
            'lu_m_u'=>'required|numeric',
            'lu_m_r'=>'required|numeric',
            'gr_d_u'=>'required|numeric',
            'gr_d_r'=>'required|numeric',
            'gr_m_u'=>'required|numeric',
            'gr_m_r'=>'required|numeric',
            'fr_d_u'=>'required|numeric',
            'fr_d_r'=>'required|numeric',
            'fr_m_u'=>'required|numeric',
            'fr_m_r'=>'required|numeric',
            'sg_d_u'=>'required|numeric',
            'sg_d_r'=>'required|numeric',
            'sg_m_u'=>'required|numeric',
            'sg_m_r'=>'required|numeric',
            'il_d_u'=>'required|numeric',
            'il_d_r'=>'required|numeric',
            'il_m_u'=>'required|numeric',
            'il_m_r'=>'required|numeric',
            'jp_d_u'=>'required|numeric',
            'jp_d_r'=>'required|numeric',
            'jp_m_u'=>'required|numeric',
            'jp_m_r'=>'required|numeric',
            'my_d_u'=>'required|numeric',
            'my_d_r'=>'required|numeric',
            'my_m_u'=>'required|numeric',
            'my_m_r'=>'required|numeric',
            'ng_d_u'=>'required|numeric',
            'ng_d_r'=>'required|numeric',
            'ng_m_u'=>'required|numeric',
            'ng_m_r'=>'required|numeric',
            'pt_d_u'=>'required|numeric',
            'pt_d_r'=>'required|numeric',
            'pt_m_u'=>'required|numeric',
            'pt_m_r'=>'required|numeric',
            'iq_d_u'=>'required|numeric',
            'iq_d_r'=>'required|numeric',
            'iq_m_u'=>'required|numeric',
            'iq_m_r'=>'required|numeric',
            'lv_d_u'=>'required|numeric',
            'lv_d_r'=>'required|numeric',
            'lv_m_u'=>'required|numeric',
            'lv_m_r'=>'required|numeric',
            'ps_d_u'=>'required|numeric',
            'ps_d_r'=>'required|numeric',
            'ps_m_u'=>'required|numeric',
            'ps_m_r'=>'required|numeric',
            'si_d_u'=>'required|numeric',
            'si_d_r'=>'required|numeric',
            'si_m_u'=>'required|numeric',
            'si_m_r'=>'required|numeric',
            'ru_d_u'=>'required|numeric',
            'ru_d_r'=>'required|numeric',
            'ru_m_u'=>'required|numeric',
            'ru_m_r'=>'required|numeric',
            'bg_d_u'=>'required|numeric',
            'bg_d_r'=>'required|numeric',
            'bg_m_u'=>'required|numeric',
            'bg_m_r'=>'required|numeric',
            'rs_d_u'=>'required|numeric',
            'rs_d_r'=>'required|numeric',
            'rs_m_u'=>'required|numeric',
            'rs_m_r'=>'required|numeric',
            'me_d_u'=>'required|numeric',
            'me_d_r'=>'required|numeric',
            'me_m_u'=>'required|numeric',
            'me_m_r'=>'required|numeric',
            'th_d_u'=>'required|numeric',
            'th_d_r'=>'required|numeric',
            'th_m_u'=>'required|numeric',
            'th_m_r'=>'required|numeric',
            'lk_d_u'=>'required|numeric',
            'lk_d_r'=>'required|numeric',
            'lk_m_u'=>'required|numeric',
            'lk_m_r'=>'required|numeric',
            'mm_d_u'=>'required|numeric',
            'mm_d_r'=>'required|numeric',
            'mm_m_u'=>'required|numeric',
            'mm_m_r'=>'required|numeric',
            'it_d_u'=>'required|numeric',
            'it_d_r'=>'required|numeric',
            'it_m_u'=>'required|numeric',
            'it_m_r'=>'required|numeric',
            'jo_d_u'=>'required|numeric',
            'jo_d_r'=>'required|numeric',
            'jo_m_u'=>'required|numeric',
            'jo_m_r'=>'required|numeric',
            'ke_d_u'=>'required|numeric',
            'ke_d_r'=>'required|numeric',
            'ke_m_u'=>'required|numeric',
            'ke_m_r'=>'required|numeric',
            'ir_d_u'=>'required|numeric',
            'ir_d_r'=>'required|numeric',
            'ir_m_u'=>'required|numeric',
            'ir_m_r'=>'required|numeric',
            'gh_d_u'=>'required|numeric',
            'gh_d_r'=>'required|numeric',
            'gh_m_u'=>'required|numeric',
            'gh_m_r'=>'required|numeric',
            'pa_d_u'=>'required|numeric',
            'pa_d_r'=>'required|numeric',
            'pa_m_u'=>'required|numeric',
            'pa_m_r'=>'required|numeric',
            'mo_d_u'=>'required|numeric',
            'mo_d_r'=>'required|numeric',
            'mo_m_u'=>'required|numeric',
            'mo_m_r'=>'required|numeric',
            'kz_d_u'=>'required|numeric',
            'kz_d_r'=>'required|numeric',
            'kz_m_u'=>'required|numeric',
            'kz_m_r'=>'required|numeric',
            'bd_d_u'=>'required|numeric',
            'bd_d_r'=>'required|numeric',
            'bd_m_u'=>'required|numeric',
            'bd_m_r'=>'required|numeric',
            'ee_d_u'=>'required|numeric',
            'ee_d_r'=>'required|numeric',
            'ee_m_u'=>'required|numeric',
            'ee_m_r'=>'required|numeric',
            'lt_d_u'=>'required|numeric',
            'lt_d_r'=>'required|numeric',
            'lt_m_u'=>'required|numeric',
            'lt_m_r'=>'required|numeric',
            'ge_d_u'=>'required|numeric',
            'ge_d_r'=>'required|numeric',
            'ge_m_u'=>'required|numeric',
            'ge_m_r'=>'required|numeric',
            'mx_d_u'=>'required|numeric',
            'mx_d_r'=>'required|numeric',
            'mx_m_u'=>'required|numeric',
            'mx_m_r'=>'required|numeric',
            'io_d_u'=>'required|numeric',
            'io_d_r'=>'required|numeric',
            'io_m_u'=>'required|numeric',
            'io_m_r'=>'required|numeric',
            'md_d_u'=>'required|numeric',
            'md_d_r'=>'required|numeric',
            'md_m_u'=>'required|numeric',
            'md_m_r'=>'required|numeric',
            'tz_d_u'=>'required|numeric',
            'tz_d_r'=>'required|numeric',
            'tz_m_u'=>'required|numeric',
            'tz_m_r'=>'required|numeric',
            'indo_d_u'=>'required|numeric',
            'indo_d_r'=>'required|numeric',
            'indo_m_u'=>'required|numeric',
            'indo_m_r'=>'required|numeric',
            'ci_d_u'=>'required|numeric',
            'ci_d_r'=>'required|numeric',
            'ci_m_u'=>'required|numeric',
            'ci_m_r'=>'required|numeric',
            'br_d_u'=>'required|numeric',
            'br_d_r'=>'required|numeric',
            'br_m_u'=>'required|numeric',
            'br_m_r'=>'required|numeric',
            'ba_d_u'=>'required|numeric',
            'ba_d_r'=>'required|numeric',
            'ba_m_u'=>'required|numeric',
            'ba_m_r'=>'required|numeric',
            'hn_d_u'=>'required|numeric',
            'hn_d_r'=>'required|numeric',
            'hn_m_u'=>'required|numeric',
            'hn_m_r'=>'required|numeric',
            'in_d_u'=>'required|numeric',
            'in_d_r'=>'required|numeric',
            'in_m_u'=>'required|numeric',
            'in_m_r'=>'required|numeric',
            'vn_d_u'=>'required|numeric',
            'vn_d_r'=>'required|numeric',
            'vn_m_u'=>'required|numeric',
            'vn_m_r'=>'required|numeric',
            'tw_d_u'=>'required|numeric',
            'tw_d_r'=>'required|numeric',
            'tw_m_u'=>'required|numeric',
            'tw_m_r'=>'required|numeric',
            'gt_d_u'=>'required|numeric',
            'gt_d_r'=>'required|numeric',
            'gt_m_u'=>'required|numeric',
            'gt_m_r'=>'required|numeric',
            'cn_d_u'=>'required|numeric',
            'cn_d_r'=>'required|numeric',
            'cn_m_u'=>'required|numeric',
            'cn_m_r'=>'required|numeric',
            'kh_d_u'=>'required|numeric',
            'kh_d_r'=>'required|numeric',
            'kh_m_u'=>'required|numeric',
            'kh_m_r'=>'required|numeric',
            'at_d_u'=>'required|numeric',
            'at_d_r'=>'required|numeric',
            'at_m_u'=>'required|numeric',
            'at_m_r'=>'required|numeric',
            'sk_d_u'=>'required|numeric',
            'sk_d_r'=>'required|numeric',
            'sk_m_u'=>'required|numeric',
            'sk_m_r'=>'required|numeric',
            'am_d_u'=>'required|numeric',
            'am_d_r'=>'required|numeric',
            'am_m_u'=>'required|numeric',
            'am_m_r'=>'required|numeric',
            'al_d_u'=>'required|numeric',
            'al_d_r'=>'required|numeric',
            'al_m_u'=>'required|numeric',
            'al_m_r'=>'required|numeric',
            'mk_d_u'=>'required|numeric',
            'mk_d_r'=>'required|numeric',
            'mk_m_u'=>'required|numeric',
            'mk_m_r'=>'required|numeric',
            'tm_d_u'=>'required|numeric',
            'tm_d_r'=>'required|numeric',
            'tm_m_u'=>'required|numeric',
            'tm_m_r'=>'required|numeric',
            'lb_d_u'=>'required|numeric',
            'lb_d_r'=>'required|numeric',
            'lb_m_u'=>'required|numeric',
            'lb_m_r'=>'required|numeric',
            'ec_d_u'=>'required|numeric',
            'ec_d_r'=>'required|numeric',
            'ec_m_u'=>'required|numeric',
            'ec_m_r'=>'required|numeric',
            'ph_d_u'=>'required|numeric',
            'ph_d_r'=>'required|numeric',
            'ph_m_u'=>'required|numeric',
            'ph_m_r'=>'required|numeric',
            'hu_d_u'=>'required|numeric',
            'hu_d_r'=>'required|numeric',
            'hu_m_u'=>'required|numeric',
            'hu_m_r'=>'required|numeric',
            'eg_d_u'=>'required|numeric',
            'eg_d_r'=>'required|numeric',
            'eg_m_u'=>'required|numeric',
            'eg_m_r'=>'required|numeric',
            'pk_d_u'=>'required|numeric',
            'pk_d_r'=>'required|numeric',
            'pk_m_u'=>'required|numeric',
            'pk_m_r'=>'required|numeric',
            'cm_d_u'=>'required|numeric',
            'cm_d_r'=>'required|numeric',
            'cm_m_u'=>'required|numeric',
            'cm_m_r'=>'required|numeric',
            'ua_d_u'=>'required|numeric',
            'ua_d_r'=>'required|numeric',
            'ua_m_u'=>'required|numeric',
            'ua_m_r'=>'required|numeric',
            'bm_d_u'=>'required|numeric',
            'bm_d_r'=>'required|numeric',
            'bm_m_u'=>'required|numeric',
            'bm_m_r'=>'required|numeric',
            'nc_d_u'=>'required|numeric',
            'nc_d_r'=>'required|numeric',
            'nc_m_u'=>'required|numeric',
            'nc_m_r'=>'required|numeric',
            'ly_d_u'=>'required|numeric',
            'ly_d_r'=>'required|numeric',
            'ly_m_u'=>'required|numeric',
            'ly_m_r'=>'required|numeric',
            'ar_d_u'=>'required|numeric',
            'ar_d_r'=>'required|numeric',
            'ar_m_u'=>'required|numeric',
            'ar_m_r'=>'required|numeric',
            'hk_d_u'=>'required|numeric',
            'hk_d_r'=>'required|numeric',
            'hk_m_u'=>'required|numeric',
            'hk_m_r'=>'required|numeric',
            'tr_d_u'=>'required|numeric',
            'tr_d_r'=>'required|numeric',
            'tr_m_u'=>'required|numeric',
            'tr_m_r'=>'required|numeric',
            'dz_d_u'=>'required|numeric',
            'dz_d_r'=>'required|numeric',
            'dz_m_u'=>'required|numeric',
            'dz_m_r'=>'required|numeric',
            'ro_d_u'=>'required|numeric',
            'ro_d_r'=>'required|numeric',
            'ro_m_u'=>'required|numeric',
            'ro_m_r'=>'required|numeric',
            'bs_d_u'=>'required|numeric',
            'bs_d_r'=>'required|numeric',
            'bs_m_u'=>'required|numeric',
            'bs_m_r'=>'required|numeric',
            'gl_d_u'=>'required|numeric',
            'gl_d_r'=>'required|numeric',
            'gl_m_u'=>'required|numeric',
            'gl_m_r'=>'required|numeric',
            'lr_d_u'=>'required|numeric',
            'lr_d_r'=>'required|numeric',
            'lr_m_u'=>'required|numeric',
            'lr_m_r'=>'required|numeric',
            'mf_d_u'=>'required|numeric',
            'mf_d_r'=>'required|numeric',
            'mf_m_u'=>'required|numeric',
            'mf_m_r'=>'required|numeric',
            'bt_d_u'=>'required|numeric',
            'bt_d_r'=>'required|numeric',
            'bt_m_u'=>'required|numeric',
            'bt_m_r'=>'required|numeric',
            'gf_d_u'=>'required|numeric',
            'gf_d_r'=>'required|numeric',
            'gf_m_u'=>'required|numeric',
            'gf_m_r'=>'required|numeric',
            'np_d_u'=>'required|numeric',
            'np_d_r'=>'required|numeric',
            'np_m_u'=>'required|numeric',
            'np_m_r'=>'required|numeric',
            'af_d_u'=>'required|numeric',
            'af_d_r'=>'required|numeric',
            'af_m_u'=>'required|numeric',
            'af_m_r'=>'required|numeric',
            'cu_d_u'=>'required|numeric',
            'cu_d_r'=>'required|numeric',
            'cu_m_u'=>'required|numeric',
            'cu_m_r'=>'required|numeric',
            'sv_d_u'=>'required|numeric',
            'sv_d_r'=>'required|numeric',
            'sv_m_u'=>'required|numeric',
            'sv_m_r'=>'required|numeric',
            'sm_d_u'=>'required|numeric',
            'sm_d_r'=>'required|numeric',
            'sm_m_u'=>'required|numeric',
            'sm_m_r'=>'required|numeric',
            'others_d_u'=>'required|numeric',
            'others_d_r'=>'required|numeric',
            'others_m_u'=>'required|numeric',
            'others_m_r'=>'required|numeric'

        ));


        $country = new country();


        $country->US  = $request->us_d_u;
        $country->US_r = $request->us_d_r;
        $country->US_m = $request->us_m_u;
        $country->US_mr = $request->us_m_r;
        $country->CA  = $request->ca_d_u;
        $country->CA_r = $request->ca_d_r;
        $country->CA_m = $request->ca_m_u;
        $country->CA_mr = $request->ca_m_r;
        $country->GB  = $request->gb_d_u;
        $country->GB_r = $request->gb_d_r;
        $country->GB_m = $request->gb_m_u;
        $country->GB_mr = $request->gb_m_r;
        $country->AU  = $request->au_d_u;
        $country->AU_r = $request->au_d_r;
        $country->AU_m = $request->au_m_u;
        $country->AU_mr = $request->au_m_r;
        $country->DE  = $request->de_d_u;
        $country->DE_r = $request->de_d_r;
        $country->DE_m = $request->de_m_u;
        $country->DE_mr = $request->de_m_r;
        $country->NO  = $request->no_d_u;
        $country->NO_r = $request->no_d_r;
        $country->NO_m = $request->no_m_u;
        $country->NO_mr = $request->no_m_r;
        $country->AE  = $request->ae_d_u;
        $country->AE_r = $request->ae_d_r;
        $country->AE_m = $request->ae_m_u;
        $country->AE_mr = $request->ae_m_r;
        $country->SE  = $request->se_d_u;
        $country->SE_r = $request->se_d_r;
        $country->SE_m = $request->se_m_u;
        $country->SE_mr = $request->se_m_r;
        $country->ZA  = $request->za_d_u;
        $country->ZA_r = $request->za_d_r;
        $country->ZA_m = $request->za_m_u;
        $country->ZA_mr = $request->za_m_r;
        $country->FI  = $request->fi_d_u;
        $country->FI_r = $request->fi_d_r;
        $country->FI_m = $request->fi_m_u;
        $country->FI_mr = $request->fi_m_r;
        $country->DK  = $request->dk_d_u;
        $country->DK_r = $request->dk_d_r;
        $country->DK_m = $request->dk_m_u;
        $country->DK_mr = $request->dk_m_r;
        $country->NZ  = $request->nz_d_u;
        $country->NZ_r = $request->nz_d_r;
        $country->NZ_m = $request->nz_m_u;
        $country->NZ_mr = $request->nz_m_r;
        $country->PL  = $request->pl_d_u;
        $country->PL_r = $request->pl_d_r;
        $country->PL_m = $request->pl_m_u;
        $country->PL_mr = $request->pl_m_r;
        $country->IE  = $request->ie_d_u;
        $country->IE_r = $request->ie_d_r;
        $country->IE_m = $request->ie_m_u;
        $country->IE_mr = $request->ie_m_r;
        $country->CH  = $request->ch_d_u;
        $country->CH_r = $request->ch_d_r;
        $country->CH_m = $request->ch_m_u;
        $country->CH_mr = $request->ch_m_r;
        $country->KW  = $request->kw_d_u;
        $country->KW_r = $request->kw_d_r;
        $country->KW_m = $request->kw_m_u;
        $country->KW_mr = $request->kw_m_r;
        $country->QA  = $request->qa_d_u;
        $country->QA_r = $request->qa_d_r;
        $country->QA_m = $request->qa_m_u;
        $country->QA_mr = $request->qa_m_r;
        $country->SA  = $request->sa_d_u;
        $country->SA_r = $request->sa_d_r;
        $country->SA_m = $request->sa_m_u;
        $country->SA_mr = $request->sa_m_r;
        $country->BE  = $request->be_d_u;
        $country->BE_r = $request->be_d_r;
        $country->BE_m = $request->be_m_u;
        $country->BE_mr = $request->be_m_r;
        $country->ES  = $request->es_d_u;
        $country->ES_r = $request->es_d_r;
        $country->ES_m = $request->es_m_u;
        $country->ES_mr = $request->es_m_r;
        $country->KR  = $request->kr_d_u;
        $country->KR_r = $request->kr_d_r;
        $country->KR_m = $request->kr_m_u;
        $country->KR_mr = $request->kr_m_r;
        $country->OM  = $request->om_d_u;
        $country->OM_r = $request->om_d_r;
        $country->OM_m = $request->om_m_u;
        $country->OM_mr = $request->om_m_r;
        $country->CY  = $request->cy_d_u;
        $country->CY_r = $request->cy_d_r;
        $country->CY_m = $request->cy_m_u;
        $country->CY_mr = $request->cy_m_r;
        $country->NL  = $request->nl_d_u;
        $country->NL_r = $request->nl_d_r;
        $country->NL_m = $request->nl_m_u;
        $country->NL_mr = $request->nl_m_r;
        $country->CZ  = $request->cz_d_u;
        $country->CZ_r = $request->cz_d_r;
        $country->CZ_m = $request->cz_m_u;
        $country->CZ_mr = $request->cz_m_r;
        $country->IS  = $request->is_d_u;
        $country->IS_r = $request->is_d_r;
        $country->IS_m = $request->is_m_u;
        $country->IS_mr = $request->is_m_r;
        $country->LU  = $request->lu_d_u;
        $country->LU_r = $request->lu_d_r;
        $country->LU_m = $request->lu_m_u;
        $country->LU_mr = $request->lu_m_r;
        $country->GR  = $request->gr_d_u;
        $country->GR_r = $request->gr_d_r;
        $country->GR_m = $request->gr_m_u;
        $country->GR_mr = $request->gr_m_r;
        $country->FR  = $request->fr_d_u;
        $country->FR_r = $request->fr_d_r;
        $country->FR_m = $request->fr_m_u;
        $country->FR_mr = $request->fr_m_r;
        $country->SG  = $request->sg_d_u;
        $country->SG_r = $request->sg_d_r;
        $country->SG_m = $request->sg_m_u;
        $country->SG_mr = $request->sg_m_r;
        $country->IL  = $request->il_d_u;
        $country->IL_r = $request->il_d_r;
        $country->IL_m = $request->il_m_u;
        $country->IL_mr = $request->il_m_r;
        $country->JP  = $request->jp_d_u;
        $country->JP_r = $request->jp_d_r;
        $country->JP_m = $request->jp_m_u;
        $country->JP_mr = $request->jp_m_r;
        $country->MY  = $request->my_d_u;
        $country->MY_r = $request->my_d_r;
        $country->MY_m = $request->my_m_u;
        $country->MY_mr = $request->my_m_r;
        $country->NG  = $request->ng_d_u;
        $country->NG_r = $request->ng_d_r;
        $country->NG_m = $request->ng_m_u;
        $country->NG_mr = $request->ng_m_r;
        $country->PT  = $request->pt_d_u;
        $country->PT_r = $request->pt_d_r;
        $country->PT_m = $request->pt_m_u;
        $country->PT_mr = $request->pt_m_r;
        $country->IQ  = $request->iq_d_u;
        $country->IQ_r = $request->iq_d_r;
        $country->IQ_m = $request->iq_m_u;
        $country->IQ_mr = $request->iq_m_r;
        $country->LV  = $request->lv_d_u;
        $country->LV_r = $request->lv_d_r;
        $country->LV_m = $request->lv_m_u;
        $country->LV_mr = $request->lv_m_r;
        $country->PS  = $request->ps_d_u;
        $country->PS_r = $request->ps_d_r;
        $country->PS_m = $request->ps_m_u;
        $country->PS_mr = $request->ps_m_r;
        $country->SI  = $request->si_d_u;
        $country->SI_r = $request->si_d_r;
        $country->SI_m = $request->si_m_u;
        $country->SI_mr = $request->si_m_r;
        $country->RU  = $request->ru_d_u;
        $country->RU_r = $request->ru_d_r;
        $country->RU_m = $request->ru_m_u;
        $country->RU_mr = $request->ru_m_r;
        $country->BG  = $request->bg_d_u;
        $country->BG_r = $request->bg_d_r;
        $country->BG_m = $request->bg_m_u;
        $country->BG_mr = $request->bg_m_r;
        $country->RS  = $request->rs_d_u;
        $country->RS_r = $request->rs_d_r;
        $country->RS_m = $request->rs_m_u;
        $country->RS_mr = $request->rs_m_r;
        $country->ME  = $request->me_d_u;
        $country->ME_r = $request->me_d_r;
        $country->ME_m = $request->me_m_u;
        $country->ME_mr = $request->me_m_r;
        $country->TH  = $request->th_d_u;
        $country->TH_r = $request->th_d_r;
        $country->TH_m = $request->th_m_u;
        $country->TH_mr = $request->th_m_r;
        $country->LK  = $request->lk_d_u;
        $country->LK_r = $request->lk_d_r;
        $country->LK_m = $request->lk_m_u;
        $country->LK_mr = $request->lk_m_r;
        $country->MM  = $request->mm_d_u;
        $country->MM_r = $request->mm_d_r;
        $country->MM_m = $request->mm_m_u;
        $country->MM_mr = $request->mm_m_r;
        $country->IT  = $request->it_d_u;
        $country->IT_r = $request->it_d_r;
        $country->IT_m = $request->it_m_u;
        $country->IT_mr = $request->it_m_r;
        $country->JO  = $request->jo_d_u;
        $country->JO_r = $request->jo_d_r;
        $country->JO_m = $request->jo_m_u;
        $country->JO_mr = $request->jo_m_r;
        $country->KE  = $request->ke_d_u;
        $country->KE_r = $request->ke_d_r;
        $country->KE_m = $request->ke_m_u;
        $country->KE_mr = $request->ke_m_r;
        $country->IR  = $request->ir_d_u;
        $country->IR_r = $request->ir_d_r;
        $country->IR_m = $request->ir_m_u;
        $country->IR_mr = $request->ir_m_r;
        $country->GH  = $request->gh_d_u;
        $country->GH_r = $request->gh_d_r;
        $country->GH_m = $request->gh_m_u;
        $country->GH_mr = $request->gh_m_r;
        $country->PA  = $request->pa_d_u;
        $country->PA_r = $request->pa_d_r;
        $country->PA_m = $request->pa_m_u;
        $country->PA_mr = $request->pa_m_r;
        $country->MO  = $request->mo_d_u;
        $country->MO_r = $request->mo_d_r;
        $country->MO_m = $request->mo_m_u;
        $country->MO_mr = $request->mo_m_r;
        $country->KZ  = $request->kz_d_u;
        $country->KZ_r = $request->kz_d_r;
        $country->KZ_m = $request->kz_m_u;
        $country->KZ_mr = $request->kz_m_r;
        $country->BD  = $request->bd_d_u;
        $country->BD_r = $request->bd_d_r;
        $country->BD_m = $request->bd_m_u;
        $country->BD_mr = $request->bd_m_r;
        $country->EE  = $request->ee_d_u;
        $country->EE_r = $request->ee_d_r;
        $country->EE_m = $request->ee_m_u;
        $country->EE_mr = $request->ee_m_r;
        $country->LT  = $request->lt_d_u;
        $country->LT_r = $request->lt_d_r;
        $country->LT_m = $request->lt_m_u;
        $country->LT_mr = $request->lt_m_r;
        $country->GE  = $request->ge_d_u;
        $country->GE_r = $request->ge_d_r;
        $country->GE_m = $request->ge_m_u;
        $country->GE_mr = $request->ge_m_r;
        $country->MX  = $request->mx_d_u;
        $country->MX_r = $request->mx_d_r;
        $country->MX_m = $request->mx_m_u;
        $country->MX_mr = $request->mx_m_r;
        $country->IO  = $request->io_d_u;
        $country->IO_r = $request->io_d_r;
        $country->IO_m = $request->io_m_u;
        $country->IO_mr = $request->io_m_r;
        $country->MD  = $request->md_d_u;
        $country->MD_r = $request->md_d_r;
        $country->MD_m = $request->md_m_u;
        $country->MD_mr = $request->md_m_r;
        $country->TZ  = $request->tz_d_u;
        $country->TZ_r = $request->tz_d_r;
        $country->TZ_m = $request->tz_m_u;
        $country->TZ_mr = $request->tz_m_r;
        $country->INDO  = $request->indo_d_u;
        $country->INDO_r = $request->indo_d_r;
        $country->INDO_m = $request->indo_m_u;
        $country->INDO_mr = $request->indo_m_r;
        $country->CI  = $request->ci_d_u;
        $country->CI_r = $request->ci_d_r;
        $country->CI_m = $request->ci_m_u;
        $country->CI_mr = $request->ci_m_r;
        $country->BR  = $request->br_d_u;
        $country->BR_r = $request->br_d_r;
        $country->BR_m = $request->br_m_u;
        $country->BR_mr = $request->br_m_r;
        $country->BA  = $request->ba_d_u;
        $country->BA_r = $request->ba_d_r;
        $country->BA_m = $request->ba_m_u;
        $country->BA_mr = $request->ba_m_r;
        $country->HN  = $request->hn_d_u;
        $country->HN_r = $request->hn_d_r;
        $country->HN_m = $request->hn_m_u;
        $country->HN_mr = $request->hn_m_r;
        $country->IN  = $request->in_d_u;
        $country->IN_r = $request->in_d_r;
        $country->IN_m = $request->in_m_u;
        $country->IN_mr = $request->in_m_r;
        $country->VN  = $request->vn_d_u;
        $country->VN_r = $request->vn_d_r;
        $country->VN_m = $request->vn_m_u;
        $country->VN_mr = $request->vn_m_r;
        $country->TW  = $request->tw_d_u;
        $country->TW_r = $request->tw_d_r;
        $country->TW_m = $request->tw_m_u;
        $country->TW_mr = $request->tw_m_r;
        $country->GT  = $request->gt_d_u;
        $country->GT_r = $request->gt_d_r;
        $country->GT_m = $request->gt_m_u;
        $country->GT_mr = $request->gt_m_r;
        $country->CN  = $request->cn_d_u;
        $country->CN_r = $request->cn_d_r;
        $country->CN_m = $request->cn_m_u;
        $country->CN_mr = $request->cn_m_r;
        $country->KH  = $request->kh_d_u;
        $country->KH_r = $request->kh_d_r;
        $country->KH_m = $request->kh_m_u;
        $country->KH_mr = $request->kh_m_r;
        $country->AT  = $request->at_d_u;
        $country->AT_r = $request->at_d_r;
        $country->AT_m = $request->at_m_u;
        $country->AT_mr = $request->at_m_r;
        $country->SK  = $request->sk_d_u;
        $country->SK_r = $request->sk_d_r;
        $country->SK_m = $request->sk_m_u;
        $country->SK_mr = $request->sk_m_r;
        $country->AM  = $request->am_d_u;
        $country->AM_r = $request->am_d_r;
        $country->AM_m = $request->am_m_u;
        $country->AM_mr = $request->am_m_r;
        $country->AL  = $request->al_d_u;
        $country->AL_r = $request->al_d_r;
        $country->AL_m = $request->al_m_u;
        $country->AL_mr = $request->al_m_r;
        $country->MK  = $request->mk_d_u;
        $country->MK_r = $request->mk_d_r;
        $country->MK_m = $request->mk_m_u;
        $country->MK_mr = $request->mk_m_r;
        $country->TM  = $request->tm_d_u;
        $country->TM_r = $request->tm_d_r;
        $country->TM_m = $request->tm_m_u;
        $country->TM_mr = $request->tm_m_r;
        $country->LB  = $request->lb_d_u;
        $country->LB_r = $request->lb_d_r;
        $country->LB_m = $request->lb_m_u;
        $country->LB_mr = $request->lb_m_r;
        $country->EC  = $request->ec_d_u;
        $country->EC_r = $request->ec_d_r;
        $country->EC_m = $request->ec_m_u;
        $country->EC_mr = $request->ec_m_r;
        $country->PH  = $request->ph_d_u;
        $country->PH_r = $request->ph_d_r;
        $country->PH_m = $request->ph_m_u;
        $country->PH_mr = $request->ph_m_r;
        $country->HU  = $request->hu_d_u;
        $country->HU_r = $request->hu_d_r;
        $country->HU_m = $request->hu_m_u;
        $country->HU_mr = $request->hu_m_r;
        $country->EG  = $request->eg_d_u;
        $country->EG_r = $request->eg_d_r;
        $country->EG_m = $request->eg_m_u;
        $country->EG_mr = $request->eg_m_r;
        $country->PK  = $request->pk_d_u;
        $country->PK_r = $request->pk_d_r;
        $country->PK_m = $request->pk_m_u;
        $country->PK_mr = $request->pk_m_r;
        $country->CM  = $request->cm_d_u;
        $country->CM_r = $request->cm_d_r;
        $country->CM_m = $request->cm_m_u;
        $country->CM_mr = $request->cm_m_r;
        $country->UA  = $request->ua_d_u;
        $country->UA_r = $request->ua_d_r;
        $country->UA_m = $request->ua_m_u;
        $country->UA_mr = $request->ua_m_r;
        $country->BM  = $request->bm_d_u;
        $country->BM_r = $request->bm_d_r;
        $country->BM_m = $request->bm_m_u;
        $country->BM_mr = $request->bm_m_r;
        $country->NC  = $request->nc_d_u;
        $country->NC_r = $request->nc_d_r;
        $country->NC_m = $request->nc_m_u;
        $country->NC_mr = $request->nc_m_r;
        $country->LY  = $request->ly_d_u;
        $country->LY_r = $request->ly_d_r;
        $country->LY_m = $request->ly_m_u;
        $country->LY_mr = $request->ly_m_r;
        $country->AR  = $request->ar_d_u;
        $country->AR_r = $request->ar_d_r;
        $country->AR_m = $request->ar_m_u;
        $country->AR_mr = $request->ar_m_r;
        $country->HK  = $request->hk_d_u;
        $country->HK_r = $request->hk_d_r;
        $country->HK_m = $request->hk_m_u;
        $country->HK_mr = $request->hk_m_r;
        $country->TR  = $request->tr_d_u;
        $country->TR_r = $request->tr_d_r;
        $country->TR_m = $request->tr_m_u;
        $country->TR_mr = $request->tr_m_r;
        $country->DZ  = $request->dz_d_u;
        $country->DZ_r = $request->dz_d_r;
        $country->DZ_m = $request->dz_m_u;
        $country->DZ_mr = $request->dz_m_r;
        $country->RO  = $request->ro_d_u;
        $country->RO_r = $request->ro_d_r;
        $country->RO_m = $request->ro_m_u;
        $country->RO_mr = $request->ro_m_r;
        $country->BS  = $request->bs_d_u;
        $country->BS_r = $request->bs_d_r;
        $country->BS_m = $request->bs_m_u;
        $country->BS_mr = $request->bs_m_r;
        $country->GL  = $request->gl_d_u;
        $country->GL_r = $request->gl_d_r;
        $country->GL_m = $request->gl_m_u;
        $country->GL_mr = $request->gl_m_r;
        $country->LR  = $request->lr_d_u;
        $country->LR_r = $request->lr_d_r;
        $country->LR_m = $request->lr_m_u;
        $country->LR_mr = $request->lr_m_r;
        $country->MF  = $request->mf_d_u;
        $country->MF_r = $request->mf_d_r;
        $country->MF_m = $request->mf_m_u;
        $country->MF_mr = $request->mf_m_r;
        $country->BT  = $request->bt_d_u;
        $country->BT_r = $request->bt_d_r;
        $country->BT_m = $request->bt_m_u;
        $country->BT_mr = $request->bt_m_r;
        $country->GF  = $request->gf_d_u;
        $country->GF_r = $request->gf_d_r;
        $country->GF_m = $request->gf_m_u;
        $country->GF_mr = $request->gf_m_r;
        $country->NP  = $request->np_d_u;
        $country->NP_r = $request->np_d_r;
        $country->NP_m = $request->np_m_u;
        $country->NP_mr = $request->np_m_r;
        $country->AF  = $request->af_d_u;
        $country->AF_r = $request->af_d_r;
        $country->AF_m = $request->af_m_u;
        $country->AF_mr = $request->af_m_r;
        $country->CU  = $request->cu_d_u;
        $country->CU_r = $request->cu_d_r;
        $country->CU_m = $request->cu_m_u;
        $country->CU_mr = $request->cu_m_r;
        $country->SV  = $request->sv_d_u;
        $country->SV_r = $request->sv_d_r;
        $country->SV_m = $request->sv_m_u;
        $country->SV_mr = $request->sv_m_r;
        $country->SM  = $request->sm_d_u;
        $country->SM_r = $request->sm_d_r;
        $country->SM_m = $request->sm_m_u;
        $country->SM_mr = $request->sm_m_r;
        $country->others  = $request->others_d_u;
        $country->others_r = $request->others_d_r;
        $country->others_m = $request->others_m_u;
        $country->others_mr = $request->others_m_r;


        $country->save();

        return Redirect::back()->withMessage('Successfully Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country =  country::find($id);

        return view('admin.crud.rates.edit', compact('country'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, array(
            'us_d_u'=>'required|numeric',
            'us_d_r'=>'required|numeric',
            'us_m_u'=>'required|numeric',
            'us_m_r'=>'required|numeric',
            'ca_d_u'=>'required|numeric',
            'ca_d_r'=>'required|numeric',
            'ca_m_u'=>'required|numeric',
            'ca_m_r'=>'required|numeric',
            'gb_d_u'=>'required|numeric',
            'gb_d_r'=>'required|numeric',
            'gb_m_u'=>'required|numeric',
            'gb_m_r'=>'required|numeric',
            'au_d_u'=>'required|numeric',
            'au_d_r'=>'required|numeric',
            'au_m_u'=>'required|numeric',
            'au_m_r'=>'required|numeric',
            'de_d_u'=>'required|numeric',
            'de_d_r'=>'required|numeric',
            'de_m_u'=>'required|numeric',
            'de_m_r'=>'required|numeric',
            'no_d_u'=>'required|numeric',
            'no_d_r'=>'required|numeric',
            'no_m_u'=>'required|numeric',
            'no_m_r'=>'required|numeric',
            'ae_d_u'=>'required|numeric',
            'ae_d_r'=>'required|numeric',
            'ae_m_u'=>'required|numeric',
            'ae_m_r'=>'required|numeric',
            'se_d_u'=>'required|numeric',
            'se_d_r'=>'required|numeric',
            'se_m_u'=>'required|numeric',
            'se_m_r'=>'required|numeric',
            'za_d_u'=>'required|numeric',
            'za_d_r'=>'required|numeric',
            'za_m_u'=>'required|numeric',
            'za_m_r'=>'required|numeric',
            'fi_d_u'=>'required|numeric',
            'fi_d_r'=>'required|numeric',
            'fi_m_u'=>'required|numeric',
            'fi_m_r'=>'required|numeric',
            'dk_d_u'=>'required|numeric',
            'dk_d_r'=>'required|numeric',
            'dk_m_u'=>'required|numeric',
            'dk_m_r'=>'required|numeric',
            'nz_d_u'=>'required|numeric',
            'nz_d_r'=>'required|numeric',
            'nz_m_u'=>'required|numeric',
            'nz_m_r'=>'required|numeric',
            'pl_d_u'=>'required|numeric',
            'pl_d_r'=>'required|numeric',
            'pl_m_u'=>'required|numeric',
            'pl_m_r'=>'required|numeric',
            'ie_d_u'=>'required|numeric',
            'ie_d_r'=>'required|numeric',
            'ie_m_u'=>'required|numeric',
            'ie_m_r'=>'required|numeric',
            'ch_d_u'=>'required|numeric',
            'ch_d_r'=>'required|numeric',
            'ch_m_u'=>'required|numeric',
            'ch_m_r'=>'required|numeric',
            'kw_d_u'=>'required|numeric',
            'kw_d_r'=>'required|numeric',
            'kw_m_u'=>'required|numeric',
            'kw_m_r'=>'required|numeric',
            'qa_d_u'=>'required|numeric',
            'qa_d_r'=>'required|numeric',
            'qa_m_u'=>'required|numeric',
            'qa_m_r'=>'required|numeric',
            'sa_d_u'=>'required|numeric',
            'sa_d_r'=>'required|numeric',
            'sa_m_u'=>'required|numeric',
            'sa_m_r'=>'required|numeric',
            'be_d_u'=>'required|numeric',
            'be_d_r'=>'required|numeric',
            'be_m_u'=>'required|numeric',
            'be_m_r'=>'required|numeric',
            'es_d_u'=>'required|numeric',
            'es_d_r'=>'required|numeric',
            'es_m_u'=>'required|numeric',
            'es_m_r'=>'required|numeric',
            'kr_d_u'=>'required|numeric',
            'kr_d_r'=>'required|numeric',
            'kr_m_u'=>'required|numeric',
            'kr_m_r'=>'required|numeric',
            'om_d_u'=>'required|numeric',
            'om_d_r'=>'required|numeric',
            'om_m_u'=>'required|numeric',
            'om_m_r'=>'required|numeric',
            'cy_d_u'=>'required|numeric',
            'cy_d_r'=>'required|numeric',
            'cy_m_u'=>'required|numeric',
            'cy_m_r'=>'required|numeric',
            'nl_d_u'=>'required|numeric',
            'nl_d_r'=>'required|numeric',
            'nl_m_u'=>'required|numeric',
            'nl_m_r'=>'required|numeric',
            'cz_d_u'=>'required|numeric',
            'cz_d_r'=>'required|numeric',
            'cz_m_u'=>'required|numeric',
            'cz_m_r'=>'required|numeric',
            'is_d_u'=>'required|numeric',
            'is_d_r'=>'required|numeric',
            'is_m_u'=>'required|numeric',
            'is_m_r'=>'required|numeric',
            'lu_d_u'=>'required|numeric',
            'lu_d_r'=>'required|numeric',
            'lu_m_u'=>'required|numeric',
            'lu_m_r'=>'required|numeric',
            'gr_d_u'=>'required|numeric',
            'gr_d_r'=>'required|numeric',
            'gr_m_u'=>'required|numeric',
            'gr_m_r'=>'required|numeric',
            'fr_d_u'=>'required|numeric',
            'fr_d_r'=>'required|numeric',
            'fr_m_u'=>'required|numeric',
            'fr_m_r'=>'required|numeric',
            'sg_d_u'=>'required|numeric',
            'sg_d_r'=>'required|numeric',
            'sg_m_u'=>'required|numeric',
            'sg_m_r'=>'required|numeric',
            'il_d_u'=>'required|numeric',
            'il_d_r'=>'required|numeric',
            'il_m_u'=>'required|numeric',
            'il_m_r'=>'required|numeric',
            'jp_d_u'=>'required|numeric',
            'jp_d_r'=>'required|numeric',
            'jp_m_u'=>'required|numeric',
            'jp_m_r'=>'required|numeric',
            'my_d_u'=>'required|numeric',
            'my_d_r'=>'required|numeric',
            'my_m_u'=>'required|numeric',
            'my_m_r'=>'required|numeric',
            'ng_d_u'=>'required|numeric',
            'ng_d_r'=>'required|numeric',
            'ng_m_u'=>'required|numeric',
            'ng_m_r'=>'required|numeric',
            'pt_d_u'=>'required|numeric',
            'pt_d_r'=>'required|numeric',
            'pt_m_u'=>'required|numeric',
            'pt_m_r'=>'required|numeric',
            'iq_d_u'=>'required|numeric',
            'iq_d_r'=>'required|numeric',
            'iq_m_u'=>'required|numeric',
            'iq_m_r'=>'required|numeric',
            'lv_d_u'=>'required|numeric',
            'lv_d_r'=>'required|numeric',
            'lv_m_u'=>'required|numeric',
            'lv_m_r'=>'required|numeric',
            'ps_d_u'=>'required|numeric',
            'ps_d_r'=>'required|numeric',
            'ps_m_u'=>'required|numeric',
            'ps_m_r'=>'required|numeric',
            'si_d_u'=>'required|numeric',
            'si_d_r'=>'required|numeric',
            'si_m_u'=>'required|numeric',
            'si_m_r'=>'required|numeric',
            'ru_d_u'=>'required|numeric',
            'ru_d_r'=>'required|numeric',
            'ru_m_u'=>'required|numeric',
            'ru_m_r'=>'required|numeric',
            'bg_d_u'=>'required|numeric',
            'bg_d_r'=>'required|numeric',
            'bg_m_u'=>'required|numeric',
            'bg_m_r'=>'required|numeric',
            'rs_d_u'=>'required|numeric',
            'rs_d_r'=>'required|numeric',
            'rs_m_u'=>'required|numeric',
            'rs_m_r'=>'required|numeric',
            'me_d_u'=>'required|numeric',
            'me_d_r'=>'required|numeric',
            'me_m_u'=>'required|numeric',
            'me_m_r'=>'required|numeric',
            'th_d_u'=>'required|numeric',
            'th_d_r'=>'required|numeric',
            'th_m_u'=>'required|numeric',
            'th_m_r'=>'required|numeric',
            'lk_d_u'=>'required|numeric',
            'lk_d_r'=>'required|numeric',
            'lk_m_u'=>'required|numeric',
            'lk_m_r'=>'required|numeric',
            'mm_d_u'=>'required|numeric',
            'mm_d_r'=>'required|numeric',
            'mm_m_u'=>'required|numeric',
            'mm_m_r'=>'required|numeric',
            'it_d_u'=>'required|numeric',
            'it_d_r'=>'required|numeric',
            'it_m_u'=>'required|numeric',
            'it_m_r'=>'required|numeric',
            'jo_d_u'=>'required|numeric',
            'jo_d_r'=>'required|numeric',
            'jo_m_u'=>'required|numeric',
            'jo_m_r'=>'required|numeric',
            'ke_d_u'=>'required|numeric',
            'ke_d_r'=>'required|numeric',
            'ke_m_u'=>'required|numeric',
            'ke_m_r'=>'required|numeric',
            'ir_d_u'=>'required|numeric',
            'ir_d_r'=>'required|numeric',
            'ir_m_u'=>'required|numeric',
            'ir_m_r'=>'required|numeric',
            'gh_d_u'=>'required|numeric',
            'gh_d_r'=>'required|numeric',
            'gh_m_u'=>'required|numeric',
            'gh_m_r'=>'required|numeric',
            'pa_d_u'=>'required|numeric',
            'pa_d_r'=>'required|numeric',
            'pa_m_u'=>'required|numeric',
            'pa_m_r'=>'required|numeric',
            'mo_d_u'=>'required|numeric',
            'mo_d_r'=>'required|numeric',
            'mo_m_u'=>'required|numeric',
            'mo_m_r'=>'required|numeric',
            'kz_d_u'=>'required|numeric',
            'kz_d_r'=>'required|numeric',
            'kz_m_u'=>'required|numeric',
            'kz_m_r'=>'required|numeric',
            'bd_d_u'=>'required|numeric',
            'bd_d_r'=>'required|numeric',
            'bd_m_u'=>'required|numeric',
            'bd_m_r'=>'required|numeric',
            'ee_d_u'=>'required|numeric',
            'ee_d_r'=>'required|numeric',
            'ee_m_u'=>'required|numeric',
            'ee_m_r'=>'required|numeric',
            'lt_d_u'=>'required|numeric',
            'lt_d_r'=>'required|numeric',
            'lt_m_u'=>'required|numeric',
            'lt_m_r'=>'required|numeric',
            'ge_d_u'=>'required|numeric',
            'ge_d_r'=>'required|numeric',
            'ge_m_u'=>'required|numeric',
            'ge_m_r'=>'required|numeric',
            'mx_d_u'=>'required|numeric',
            'mx_d_r'=>'required|numeric',
            'mx_m_u'=>'required|numeric',
            'mx_m_r'=>'required|numeric',
            'io_d_u'=>'required|numeric',
            'io_d_r'=>'required|numeric',
            'io_m_u'=>'required|numeric',
            'io_m_r'=>'required|numeric',
            'md_d_u'=>'required|numeric',
            'md_d_r'=>'required|numeric',
            'md_m_u'=>'required|numeric',
            'md_m_r'=>'required|numeric',
            'tz_d_u'=>'required|numeric',
            'tz_d_r'=>'required|numeric',
            'tz_m_u'=>'required|numeric',
            'tz_m_r'=>'required|numeric',
            'indo_d_u'=>'required|numeric',
            'indo_d_r'=>'required|numeric',
            'indo_m_u'=>'required|numeric',
            'indo_m_r'=>'required|numeric',
            'ci_d_u'=>'required|numeric',
            'ci_d_r'=>'required|numeric',
            'ci_m_u'=>'required|numeric',
            'ci_m_r'=>'required|numeric',
            'br_d_u'=>'required|numeric',
            'br_d_r'=>'required|numeric',
            'br_m_u'=>'required|numeric',
            'br_m_r'=>'required|numeric',
            'ba_d_u'=>'required|numeric',
            'ba_d_r'=>'required|numeric',
            'ba_m_u'=>'required|numeric',
            'ba_m_r'=>'required|numeric',
            'hn_d_u'=>'required|numeric',
            'hn_d_r'=>'required|numeric',
            'hn_m_u'=>'required|numeric',
            'hn_m_r'=>'required|numeric',
            'in_d_u'=>'required|numeric',
            'in_d_r'=>'required|numeric',
            'in_m_u'=>'required|numeric',
            'in_m_r'=>'required|numeric',
            'vn_d_u'=>'required|numeric',
            'vn_d_r'=>'required|numeric',
            'vn_m_u'=>'required|numeric',
            'vn_m_r'=>'required|numeric',
            'tw_d_u'=>'required|numeric',
            'tw_d_r'=>'required|numeric',
            'tw_m_u'=>'required|numeric',
            'tw_m_r'=>'required|numeric',
            'gt_d_u'=>'required|numeric',
            'gt_d_r'=>'required|numeric',
            'gt_m_u'=>'required|numeric',
            'gt_m_r'=>'required|numeric',
            'cn_d_u'=>'required|numeric',
            'cn_d_r'=>'required|numeric',
            'cn_m_u'=>'required|numeric',
            'cn_m_r'=>'required|numeric',
            'kh_d_u'=>'required|numeric',
            'kh_d_r'=>'required|numeric',
            'kh_m_u'=>'required|numeric',
            'kh_m_r'=>'required|numeric',
            'at_d_u'=>'required|numeric',
            'at_d_r'=>'required|numeric',
            'at_m_u'=>'required|numeric',
            'at_m_r'=>'required|numeric',
            'sk_d_u'=>'required|numeric',
            'sk_d_r'=>'required|numeric',
            'sk_m_u'=>'required|numeric',
            'sk_m_r'=>'required|numeric',
            'am_d_u'=>'required|numeric',
            'am_d_r'=>'required|numeric',
            'am_m_u'=>'required|numeric',
            'am_m_r'=>'required|numeric',
            'al_d_u'=>'required|numeric',
            'al_d_r'=>'required|numeric',
            'al_m_u'=>'required|numeric',
            'al_m_r'=>'required|numeric',
            'mk_d_u'=>'required|numeric',
            'mk_d_r'=>'required|numeric',
            'mk_m_u'=>'required|numeric',
            'mk_m_r'=>'required|numeric',
            'tm_d_u'=>'required|numeric',
            'tm_d_r'=>'required|numeric',
            'tm_m_u'=>'required|numeric',
            'tm_m_r'=>'required|numeric',
            'lb_d_u'=>'required|numeric',
            'lb_d_r'=>'required|numeric',
            'lb_m_u'=>'required|numeric',
            'lb_m_r'=>'required|numeric',
            'ec_d_u'=>'required|numeric',
            'ec_d_r'=>'required|numeric',
            'ec_m_u'=>'required|numeric',
            'ec_m_r'=>'required|numeric',
            'ph_d_u'=>'required|numeric',
            'ph_d_r'=>'required|numeric',
            'ph_m_u'=>'required|numeric',
            'ph_m_r'=>'required|numeric',
            'hu_d_u'=>'required|numeric',
            'hu_d_r'=>'required|numeric',
            'hu_m_u'=>'required|numeric',
            'hu_m_r'=>'required|numeric',
            'eg_d_u'=>'required|numeric',
            'eg_d_r'=>'required|numeric',
            'eg_m_u'=>'required|numeric',
            'eg_m_r'=>'required|numeric',
            'pk_d_u'=>'required|numeric',
            'pk_d_r'=>'required|numeric',
            'pk_m_u'=>'required|numeric',
            'pk_m_r'=>'required|numeric',
            'cm_d_u'=>'required|numeric',
            'cm_d_r'=>'required|numeric',
            'cm_m_u'=>'required|numeric',
            'cm_m_r'=>'required|numeric',
            'ua_d_u'=>'required|numeric',
            'ua_d_r'=>'required|numeric',
            'ua_m_u'=>'required|numeric',
            'ua_m_r'=>'required|numeric',
            'bm_d_u'=>'required|numeric',
            'bm_d_r'=>'required|numeric',
            'bm_m_u'=>'required|numeric',
            'bm_m_r'=>'required|numeric',
            'nc_d_u'=>'required|numeric',
            'nc_d_r'=>'required|numeric',
            'nc_m_u'=>'required|numeric',
            'nc_m_r'=>'required|numeric',
            'ly_d_u'=>'required|numeric',
            'ly_d_r'=>'required|numeric',
            'ly_m_u'=>'required|numeric',
            'ly_m_r'=>'required|numeric',
            'ar_d_u'=>'required|numeric',
            'ar_d_r'=>'required|numeric',
            'ar_m_u'=>'required|numeric',
            'ar_m_r'=>'required|numeric',
            'hk_d_u'=>'required|numeric',
            'hk_d_r'=>'required|numeric',
            'hk_m_u'=>'required|numeric',
            'hk_m_r'=>'required|numeric',
            'tr_d_u'=>'required|numeric',
            'tr_d_r'=>'required|numeric',
            'tr_m_u'=>'required|numeric',
            'tr_m_r'=>'required|numeric',
            'dz_d_u'=>'required|numeric',
            'dz_d_r'=>'required|numeric',
            'dz_m_u'=>'required|numeric',
            'dz_m_r'=>'required|numeric',
            'ro_d_u'=>'required|numeric',
            'ro_d_r'=>'required|numeric',
            'ro_m_u'=>'required|numeric',
            'ro_m_r'=>'required|numeric',
            'bs_d_u'=>'required|numeric',
            'bs_d_r'=>'required|numeric',
            'bs_m_u'=>'required|numeric',
            'bs_m_r'=>'required|numeric',
            'gl_d_u'=>'required|numeric',
            'gl_d_r'=>'required|numeric',
            'gl_m_u'=>'required|numeric',
            'gl_m_r'=>'required|numeric',
            'lr_d_u'=>'required|numeric',
            'lr_d_r'=>'required|numeric',
            'lr_m_u'=>'required|numeric',
            'lr_m_r'=>'required|numeric',
            'mf_d_u'=>'required|numeric',
            'mf_d_r'=>'required|numeric',
            'mf_m_u'=>'required|numeric',
            'mf_m_r'=>'required|numeric',
            'bt_d_u'=>'required|numeric',
            'bt_d_r'=>'required|numeric',
            'bt_m_u'=>'required|numeric',
            'bt_m_r'=>'required|numeric',
            'gf_d_u'=>'required|numeric',
            'gf_d_r'=>'required|numeric',
            'gf_m_u'=>'required|numeric',
            'gf_m_r'=>'required|numeric',
            'np_d_u'=>'required|numeric',
            'np_d_r'=>'required|numeric',
            'np_m_u'=>'required|numeric',
            'np_m_r'=>'required|numeric',
            'af_d_u'=>'required|numeric',
            'af_d_r'=>'required|numeric',
            'af_m_u'=>'required|numeric',
            'af_m_r'=>'required|numeric',
            'cu_d_u'=>'required|numeric',
            'cu_d_r'=>'required|numeric',
            'cu_m_u'=>'required|numeric',
            'cu_m_r'=>'required|numeric',
            'sv_d_u'=>'required|numeric',
            'sv_d_r'=>'required|numeric',
            'sv_m_u'=>'required|numeric',
            'sv_m_r'=>'required|numeric',
            'sm_d_u'=>'required|numeric',
            'sm_d_r'=>'required|numeric',
            'sm_m_u'=>'required|numeric',
            'sm_m_r'=>'required|numeric',
            'others_d_u'=>'required|numeric',
            'others_d_r'=>'required|numeric',
            'others_m_u'=>'required|numeric',
            'others_m_r'=>'required|numeric'

        ));
        $country =  country::find($id);


        $country->US  = $request->us_d_u;
        $country->US_r = $request->us_d_r;
        $country->US_m = $request->us_m_u;
        $country->US_mr = $request->us_m_r;
        $country->CA  = $request->ca_d_u;
        $country->CA_r = $request->ca_d_r;
        $country->CA_m = $request->ca_m_u;
        $country->CA_mr = $request->ca_m_r;
        $country->GB  = $request->gb_d_u;
        $country->GB_r = $request->gb_d_r;
        $country->GB_m = $request->gb_m_u;
        $country->GB_mr = $request->gb_m_r;
        $country->AU  = $request->au_d_u;
        $country->AU_r = $request->au_d_r;
        $country->AU_m = $request->au_m_u;
        $country->AU_mr = $request->au_m_r;
        $country->DE  = $request->de_d_u;
        $country->DE_r = $request->de_d_r;
        $country->DE_m = $request->de_m_u;
        $country->DE_mr = $request->de_m_r;
        $country->NO  = $request->no_d_u;
        $country->NO_r = $request->no_d_r;
        $country->NO_m = $request->no_m_u;
        $country->NO_mr = $request->no_m_r;
        $country->AE  = $request->ae_d_u;
        $country->AE_r = $request->ae_d_r;
        $country->AE_m = $request->ae_m_u;
        $country->AE_mr = $request->ae_m_r;
        $country->SE  = $request->se_d_u;
        $country->SE_r = $request->se_d_r;
        $country->SE_m = $request->se_m_u;
        $country->SE_mr = $request->se_m_r;
        $country->ZA  = $request->za_d_u;
        $country->ZA_r = $request->za_d_r;
        $country->ZA_m = $request->za_m_u;
        $country->ZA_mr = $request->za_m_r;
        $country->FI  = $request->fi_d_u;
        $country->FI_r = $request->fi_d_r;
        $country->FI_m = $request->fi_m_u;
        $country->FI_mr = $request->fi_m_r;
        $country->DK  = $request->dk_d_u;
        $country->DK_r = $request->dk_d_r;
        $country->DK_m = $request->dk_m_u;
        $country->DK_mr = $request->dk_m_r;
        $country->NZ  = $request->nz_d_u;
        $country->NZ_r = $request->nz_d_r;
        $country->NZ_m = $request->nz_m_u;
        $country->NZ_mr = $request->nz_m_r;
        $country->PL  = $request->pl_d_u;
        $country->PL_r = $request->pl_d_r;
        $country->PL_m = $request->pl_m_u;
        $country->PL_mr = $request->pl_m_r;
        $country->IE  = $request->ie_d_u;
        $country->IE_r = $request->ie_d_r;
        $country->IE_m = $request->ie_m_u;
        $country->IE_mr = $request->ie_m_r;
        $country->CH  = $request->ch_d_u;
        $country->CH_r = $request->ch_d_r;
        $country->CH_m = $request->ch_m_u;
        $country->CH_mr = $request->ch_m_r;
        $country->KW  = $request->kw_d_u;
        $country->KW_r = $request->kw_d_r;
        $country->KW_m = $request->kw_m_u;
        $country->KW_mr = $request->kw_m_r;
        $country->QA  = $request->qa_d_u;
        $country->QA_r = $request->qa_d_r;
        $country->QA_m = $request->qa_m_u;
        $country->QA_mr = $request->qa_m_r;
        $country->SA  = $request->sa_d_u;
        $country->SA_r = $request->sa_d_r;
        $country->SA_m = $request->sa_m_u;
        $country->SA_mr = $request->sa_m_r;
        $country->BE  = $request->be_d_u;
        $country->BE_r = $request->be_d_r;
        $country->BE_m = $request->be_m_u;
        $country->BE_mr = $request->be_m_r;
        $country->ES  = $request->es_d_u;
        $country->ES_r = $request->es_d_r;
        $country->ES_m = $request->es_m_u;
        $country->ES_mr = $request->es_m_r;
        $country->KR  = $request->kr_d_u;
        $country->KR_r = $request->kr_d_r;
        $country->KR_m = $request->kr_m_u;
        $country->KR_mr = $request->kr_m_r;
        $country->OM  = $request->om_d_u;
        $country->OM_r = $request->om_d_r;
        $country->OM_m = $request->om_m_u;
        $country->OM_mr = $request->om_m_r;
        $country->CY  = $request->cy_d_u;
        $country->CY_r = $request->cy_d_r;
        $country->CY_m = $request->cy_m_u;
        $country->CY_mr = $request->cy_m_r;
        $country->NL  = $request->nl_d_u;
        $country->NL_r = $request->nl_d_r;
        $country->NL_m = $request->nl_m_u;
        $country->NL_mr = $request->nl_m_r;
        $country->CZ  = $request->cz_d_u;
        $country->CZ_r = $request->cz_d_r;
        $country->CZ_m = $request->cz_m_u;
        $country->CZ_mr = $request->cz_m_r;
        $country->IS  = $request->is_d_u;
        $country->IS_r = $request->is_d_r;
        $country->IS_m = $request->is_m_u;
        $country->IS_mr = $request->is_m_r;
        $country->LU  = $request->lu_d_u;
        $country->LU_r = $request->lu_d_r;
        $country->LU_m = $request->lu_m_u;
        $country->LU_mr = $request->lu_m_r;
        $country->GR  = $request->gr_d_u;
        $country->GR_r = $request->gr_d_r;
        $country->GR_m = $request->gr_m_u;
        $country->GR_mr = $request->gr_m_r;
        $country->FR  = $request->fr_d_u;
        $country->FR_r = $request->fr_d_r;
        $country->FR_m = $request->fr_m_u;
        $country->FR_mr = $request->fr_m_r;
        $country->SG  = $request->sg_d_u;
        $country->SG_r = $request->sg_d_r;
        $country->SG_m = $request->sg_m_u;
        $country->SG_mr = $request->sg_m_r;
        $country->IL  = $request->il_d_u;
        $country->IL_r = $request->il_d_r;
        $country->IL_m = $request->il_m_u;
        $country->IL_mr = $request->il_m_r;
        $country->JP  = $request->jp_d_u;
        $country->JP_r = $request->jp_d_r;
        $country->JP_m = $request->jp_m_u;
        $country->JP_mr = $request->jp_m_r;
        $country->MY  = $request->my_d_u;
        $country->MY_r = $request->my_d_r;
        $country->MY_m = $request->my_m_u;
        $country->MY_mr = $request->my_m_r;
        $country->NG  = $request->ng_d_u;
        $country->NG_r = $request->ng_d_r;
        $country->NG_m = $request->ng_m_u;
        $country->NG_mr = $request->ng_m_r;
        $country->PT  = $request->pt_d_u;
        $country->PT_r = $request->pt_d_r;
        $country->PT_m = $request->pt_m_u;
        $country->PT_mr = $request->pt_m_r;
        $country->IQ  = $request->iq_d_u;
        $country->IQ_r = $request->iq_d_r;
        $country->IQ_m = $request->iq_m_u;
        $country->IQ_mr = $request->iq_m_r;
        $country->LV  = $request->lv_d_u;
        $country->LV_r = $request->lv_d_r;
        $country->LV_m = $request->lv_m_u;
        $country->LV_mr = $request->lv_m_r;
        $country->PS  = $request->ps_d_u;
        $country->PS_r = $request->ps_d_r;
        $country->PS_m = $request->ps_m_u;
        $country->PS_mr = $request->ps_m_r;
        $country->SI  = $request->si_d_u;
        $country->SI_r = $request->si_d_r;
        $country->SI_m = $request->si_m_u;
        $country->SI_mr = $request->si_m_r;
        $country->RU  = $request->ru_d_u;
        $country->RU_r = $request->ru_d_r;
        $country->RU_m = $request->ru_m_u;
        $country->RU_mr = $request->ru_m_r;
        $country->BG  = $request->bg_d_u;
        $country->BG_r = $request->bg_d_r;
        $country->BG_m = $request->bg_m_u;
        $country->BG_mr = $request->bg_m_r;
        $country->RS  = $request->rs_d_u;
        $country->RS_r = $request->rs_d_r;
        $country->RS_m = $request->rs_m_u;
        $country->RS_mr = $request->rs_m_r;
        $country->ME  = $request->me_d_u;
        $country->ME_r = $request->me_d_r;
        $country->ME_m = $request->me_m_u;
        $country->ME_mr = $request->me_m_r;
        $country->TH  = $request->th_d_u;
        $country->TH_r = $request->th_d_r;
        $country->TH_m = $request->th_m_u;
        $country->TH_mr = $request->th_m_r;
        $country->LK  = $request->lk_d_u;
        $country->LK_r = $request->lk_d_r;
        $country->LK_m = $request->lk_m_u;
        $country->LK_mr = $request->lk_m_r;
        $country->MM  = $request->mm_d_u;
        $country->MM_r = $request->mm_d_r;
        $country->MM_m = $request->mm_m_u;
        $country->MM_mr = $request->mm_m_r;
        $country->IT  = $request->it_d_u;
        $country->IT_r = $request->it_d_r;
        $country->IT_m = $request->it_m_u;
        $country->IT_mr = $request->it_m_r;
        $country->JO  = $request->jo_d_u;
        $country->JO_r = $request->jo_d_r;
        $country->JO_m = $request->jo_m_u;
        $country->JO_mr = $request->jo_m_r;
        $country->KE  = $request->ke_d_u;
        $country->KE_r = $request->ke_d_r;
        $country->KE_m = $request->ke_m_u;
        $country->KE_mr = $request->ke_m_r;
        $country->IR  = $request->ir_d_u;
        $country->IR_r = $request->ir_d_r;
        $country->IR_m = $request->ir_m_u;
        $country->IR_mr = $request->ir_m_r;
        $country->GH  = $request->gh_d_u;
        $country->GH_r = $request->gh_d_r;
        $country->GH_m = $request->gh_m_u;
        $country->GH_mr = $request->gh_m_r;
        $country->PA  = $request->pa_d_u;
        $country->PA_r = $request->pa_d_r;
        $country->PA_m = $request->pa_m_u;
        $country->PA_mr = $request->pa_m_r;
        $country->MO  = $request->mo_d_u;
        $country->MO_r = $request->mo_d_r;
        $country->MO_m = $request->mo_m_u;
        $country->MO_mr = $request->mo_m_r;
        $country->KZ  = $request->kz_d_u;
        $country->KZ_r = $request->kz_d_r;
        $country->KZ_m = $request->kz_m_u;
        $country->KZ_mr = $request->kz_m_r;
        $country->BD  = $request->bd_d_u;
        $country->BD_r = $request->bd_d_r;
        $country->BD_m = $request->bd_m_u;
        $country->BD_mr = $request->bd_m_r;
        $country->EE  = $request->ee_d_u;
        $country->EE_r = $request->ee_d_r;
        $country->EE_m = $request->ee_m_u;
        $country->EE_mr = $request->ee_m_r;
        $country->LT  = $request->lt_d_u;
        $country->LT_r = $request->lt_d_r;
        $country->LT_m = $request->lt_m_u;
        $country->LT_mr = $request->lt_m_r;
        $country->GE  = $request->ge_d_u;
        $country->GE_r = $request->ge_d_r;
        $country->GE_m = $request->ge_m_u;
        $country->GE_mr = $request->ge_m_r;
        $country->MX  = $request->mx_d_u;
        $country->MX_r = $request->mx_d_r;
        $country->MX_m = $request->mx_m_u;
        $country->MX_mr = $request->mx_m_r;
        $country->IO  = $request->io_d_u;
        $country->IO_r = $request->io_d_r;
        $country->IO_m = $request->io_m_u;
        $country->IO_mr = $request->io_m_r;
        $country->MD  = $request->md_d_u;
        $country->MD_r = $request->md_d_r;
        $country->MD_m = $request->md_m_u;
        $country->MD_mr = $request->md_m_r;
        $country->TZ  = $request->tz_d_u;
        $country->TZ_r = $request->tz_d_r;
        $country->TZ_m = $request->tz_m_u;
        $country->TZ_mr = $request->tz_m_r;
        $country->INDO  = $request->indo_d_u;
        $country->INDO_r = $request->indo_d_r;
        $country->INDO_m = $request->indo_m_u;
        $country->INDO_mr = $request->indo_m_r;
        $country->CI  = $request->ci_d_u;
        $country->CI_r = $request->ci_d_r;
        $country->CI_m = $request->ci_m_u;
        $country->CI_mr = $request->ci_m_r;
        $country->BR  = $request->br_d_u;
        $country->BR_r = $request->br_d_r;
        $country->BR_m = $request->br_m_u;
        $country->BR_mr = $request->br_m_r;
        $country->BA  = $request->ba_d_u;
        $country->BA_r = $request->ba_d_r;
        $country->BA_m = $request->ba_m_u;
        $country->BA_mr = $request->ba_m_r;
        $country->HN  = $request->hn_d_u;
        $country->HN_r = $request->hn_d_r;
        $country->HN_m = $request->hn_m_u;
        $country->HN_mr = $request->hn_m_r;
        $country->IN  = $request->in_d_u;
        $country->IN_r = $request->in_d_r;
        $country->IN_m = $request->in_m_u;
        $country->IN_mr = $request->in_m_r;
        $country->VN  = $request->vn_d_u;
        $country->VN_r = $request->vn_d_r;
        $country->VN_m = $request->vn_m_u;
        $country->VN_mr = $request->vn_m_r;
        $country->TW  = $request->tw_d_u;
        $country->TW_r = $request->tw_d_r;
        $country->TW_m = $request->tw_m_u;
        $country->TW_mr = $request->tw_m_r;
        $country->GT  = $request->gt_d_u;
        $country->GT_r = $request->gt_d_r;
        $country->GT_m = $request->gt_m_u;
        $country->GT_mr = $request->gt_m_r;
        $country->CN  = $request->cn_d_u;
        $country->CN_r = $request->cn_d_r;
        $country->CN_m = $request->cn_m_u;
        $country->CN_mr = $request->cn_m_r;
        $country->KH  = $request->kh_d_u;
        $country->KH_r = $request->kh_d_r;
        $country->KH_m = $request->kh_m_u;
        $country->KH_mr = $request->kh_m_r;
        $country->AT  = $request->at_d_u;
        $country->AT_r = $request->at_d_r;
        $country->AT_m = $request->at_m_u;
        $country->AT_mr = $request->at_m_r;
        $country->SK  = $request->sk_d_u;
        $country->SK_r = $request->sk_d_r;
        $country->SK_m = $request->sk_m_u;
        $country->SK_mr = $request->sk_m_r;
        $country->AM  = $request->am_d_u;
        $country->AM_r = $request->am_d_r;
        $country->AM_m = $request->am_m_u;
        $country->AM_mr = $request->am_m_r;
        $country->AL  = $request->al_d_u;
        $country->AL_r = $request->al_d_r;
        $country->AL_m = $request->al_m_u;
        $country->AL_mr = $request->al_m_r;
        $country->MK  = $request->mk_d_u;
        $country->MK_r = $request->mk_d_r;
        $country->MK_m = $request->mk_m_u;
        $country->MK_mr = $request->mk_m_r;
        $country->TM  = $request->tm_d_u;
        $country->TM_r = $request->tm_d_r;
        $country->TM_m = $request->tm_m_u;
        $country->TM_mr = $request->tm_m_r;
        $country->LB  = $request->lb_d_u;
        $country->LB_r = $request->lb_d_r;
        $country->LB_m = $request->lb_m_u;
        $country->LB_mr = $request->lb_m_r;
        $country->EC  = $request->ec_d_u;
        $country->EC_r = $request->ec_d_r;
        $country->EC_m = $request->ec_m_u;
        $country->EC_mr = $request->ec_m_r;
        $country->PH  = $request->ph_d_u;
        $country->PH_r = $request->ph_d_r;
        $country->PH_m = $request->ph_m_u;
        $country->PH_mr = $request->ph_m_r;
        $country->HU  = $request->hu_d_u;
        $country->HU_r = $request->hu_d_r;
        $country->HU_m = $request->hu_m_u;
        $country->HU_mr = $request->hu_m_r;
        $country->EG  = $request->eg_d_u;
        $country->EG_r = $request->eg_d_r;
        $country->EG_m = $request->eg_m_u;
        $country->EG_mr = $request->eg_m_r;
        $country->PK  = $request->pk_d_u;
        $country->PK_r = $request->pk_d_r;
        $country->PK_m = $request->pk_m_u;
        $country->PK_mr = $request->pk_m_r;
        $country->CM  = $request->cm_d_u;
        $country->CM_r = $request->cm_d_r;
        $country->CM_m = $request->cm_m_u;
        $country->CM_mr = $request->cm_m_r;
        $country->UA  = $request->ua_d_u;
        $country->UA_r = $request->ua_d_r;
        $country->UA_m = $request->ua_m_u;
        $country->UA_mr = $request->ua_m_r;
        $country->BM  = $request->bm_d_u;
        $country->BM_r = $request->bm_d_r;
        $country->BM_m = $request->bm_m_u;
        $country->BM_mr = $request->bm_m_r;
        $country->NC  = $request->nc_d_u;
        $country->NC_r = $request->nc_d_r;
        $country->NC_m = $request->nc_m_u;
        $country->NC_mr = $request->nc_m_r;
        $country->LY  = $request->ly_d_u;
        $country->LY_r = $request->ly_d_r;
        $country->LY_m = $request->ly_m_u;
        $country->LY_mr = $request->ly_m_r;
        $country->AR  = $request->ar_d_u;
        $country->AR_r = $request->ar_d_r;
        $country->AR_m = $request->ar_m_u;
        $country->AR_mr = $request->ar_m_r;
        $country->HK  = $request->hk_d_u;
        $country->HK_r = $request->hk_d_r;
        $country->HK_m = $request->hk_m_u;
        $country->HK_mr = $request->hk_m_r;
        $country->TR  = $request->tr_d_u;
        $country->TR_r = $request->tr_d_r;
        $country->TR_m = $request->tr_m_u;
        $country->TR_mr = $request->tr_m_r;
        $country->DZ  = $request->dz_d_u;
        $country->DZ_r = $request->dz_d_r;
        $country->DZ_m = $request->dz_m_u;
        $country->DZ_mr = $request->dz_m_r;
        $country->RO  = $request->ro_d_u;
        $country->RO_r = $request->ro_d_r;
        $country->RO_m = $request->ro_m_u;
        $country->RO_mr = $request->ro_m_r;
        $country->BS  = $request->bs_d_u;
        $country->BS_r = $request->bs_d_r;
        $country->BS_m = $request->bs_m_u;
        $country->BS_mr = $request->bs_m_r;
        $country->GL  = $request->gl_d_u;
        $country->GL_r = $request->gl_d_r;
        $country->GL_m = $request->gl_m_u;
        $country->GL_mr = $request->gl_m_r;
        $country->LR  = $request->lr_d_u;
        $country->LR_r = $request->lr_d_r;
        $country->LR_m = $request->lr_m_u;
        $country->LR_mr = $request->lr_m_r;
        $country->MF  = $request->mf_d_u;
        $country->MF_r = $request->mf_d_r;
        $country->MF_m = $request->mf_m_u;
        $country->MF_mr = $request->mf_m_r;
        $country->BT  = $request->bt_d_u;
        $country->BT_r = $request->bt_d_r;
        $country->BT_m = $request->bt_m_u;
        $country->BT_mr = $request->bt_m_r;
        $country->GF  = $request->gf_d_u;
        $country->GF_r = $request->gf_d_r;
        $country->GF_m = $request->gf_m_u;
        $country->GF_mr = $request->gf_m_r;
        $country->NP  = $request->np_d_u;
        $country->NP_r = $request->np_d_r;
        $country->NP_m = $request->np_m_u;
        $country->NP_mr = $request->np_m_r;
        $country->AF  = $request->af_d_u;
        $country->AF_r = $request->af_d_r;
        $country->AF_m = $request->af_m_u;
        $country->AF_mr = $request->af_m_r;
        $country->CU  = $request->cu_d_u;
        $country->CU_r = $request->cu_d_r;
        $country->CU_m = $request->cu_m_u;
        $country->CU_mr = $request->cu_m_r;
        $country->SV  = $request->sv_d_u;
        $country->SV_r = $request->sv_d_r;
        $country->SV_m = $request->sv_m_u;
        $country->SV_mr = $request->sv_m_r;
        $country->SM  = $request->sm_d_u;
        $country->SM_r = $request->sm_d_r;
        $country->SM_m = $request->sm_m_u;
        $country->SM_mr = $request->sm_m_r;
        $country->others  = $request->others_d_u;
        $country->others_r = $request->others_d_r;
        $country->others_m = $request->others_m_u;
        $country->others_mr = $request->others_m_r;


        $country->save();

        return Redirect::back()->withMessage('Successfully Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
